import { bank } from "./helpers";

const q = bank("compgov", "compgov-u3");

export const compgovU3Questions = [
  q({
    id: "cg3-01",
    topicId: "comp-political-culture",
    difficulty: "medium",
    concept: "State-directed socialization",
    stem: "China's patriotic education campaigns in schools are best described as an example of",
    choices: [
      ["pluralist socialization through independent civil society", "The campaigns are directed by the state, not independent groups."],
      ["the state acting as an agent of political socialization", "Correct. The party uses schools to shape political values and support."],
      ["a life-cycle effect", "Life-cycle effects come from aging and changing circumstances."],
      ["a decline in state legitimacy", "The campaigns aim to reinforce, not reflect a decline in, legitimacy."],
    ],
    answer: "B",
    explanation: "In authoritarian regimes, the state often plays a central role in socialization through schools, media, and campaigns.",
    countryIds: ["china"],
  }),
  q({
    id: "cg3-02",
    topicId: "comp-political-culture",
    difficulty: "easy",
    concept: "Populism",
    stem: "A political leader claims to speak for \"the ordinary people\" against a \"corrupt elite\" that has betrayed the nation. This rhetoric is most characteristic of",
    choices: [
      ["populism", "Correct. Populism frames politics as a struggle between the people and elites."],
      ["corporatism", "Corporatism concerns state-recognized interest representation."],
      ["federalism", "Federalism is a territorial division of power."],
      ["communism", "Communism is an ideology about class and collective ownership."],
    ],
    answer: "A",
    explanation: "Populism can combine with left- or right-wing ideologies; its defining feature is the people-versus-elite framing.",
  }),
  q({
    id: "cg3-03",
    topicId: "comp-political-culture",
    difficulty: "hard",
    concept: "Ideology and regime legitimacy",
    stem: "Which pairing correctly matches a course country with an ideology its regime uses to justify its rule?",
    choices: [
      ["United Kingdom — guardianship of the Islamic jurist", "This describes Iran."],
      ["Iran — socialism with Chinese characteristics", "This describes China."],
      ["China — socialism with Chinese characteristics", "Correct. The Communist Party uses this formulation to combine markets with party rule."],
      ["Nigeria — Marxism-Leninism", "Nigeria's regime does not rest on Marxism-Leninism."],
    ],
    answer: "C",
    explanation: "Regimes use ideology to justify rule: China's party blends communist ideology with market reforms; Iran's rests on velayat-e faqih.",
    countryIds: ["china", "iran"],
  }),
  q({
    id: "cg3-04",
    topicId: "comp-participation",
    difficulty: "medium",
    concept: "Protest movements",
    stem: "Nigeria's 2020 EndSARS protests were primarily directed against",
    choices: [
      ["the removal of fuel subsidies", "Fuel subsidy removal occurred in 2023."],
      ["the results of a presidential election", "The protests focused on police conduct."],
      ["the adoption of sharia law", "Sharia law in northern states was not the focus."],
      ["abuses by a police unit", "Correct. Protesters demanded the disbanding of the Special Anti-Robbery Squad."],
    ],
    answer: "D",
    explanation: "EndSARS showed the power of youth-led, social-media-organized protest — and the limits of state responsiveness after a violent crackdown.",
    countryIds: ["nigeria"],
  }),
  q({
    id: "cg3-05",
    topicId: "comp-participation",
    difficulty: "medium",
    concept: "Mobilized participation",
    stem: "An authoritarian government organizes large rallies and pressures public employees to attend and vote. This is an example of",
    choices: [
      ["mobilized (coerced) participation", "Correct. The state directs participation to display support."],
      ["voluntary participation", "Pressure from the state makes participation not fully voluntary."],
      ["pluralism", "Pluralism involves independent groups competing for influence."],
      ["devolution", "Devolution transfers power to regional governments."],
    ],
    answer: "A",
    explanation: "Authoritarian regimes may encourage participation that shows support while restricting independent political activity.",
  }),
  q({
    id: "cg3-06",
    topicId: "comp-participation",
    difficulty: "hard",
    concept: "Protest and state response",
    stem: "The 2022 protests in Iran following the death of Mahsa Amini in custody are best described as",
    choices: [
      ["a campaign by reformist parties to win Majles seats", "The protests were a broad social movement, not an electoral campaign."],
      ["a mass movement challenging mandatory hijab laws and the regime, met with a harsh crackdown", "Correct. Protesters used the slogan \"Woman, Life, Freedom,\" and the state responded with arrests and force."],
      ["a government-organized rally supporting the Supreme Leader", "The protests opposed the regime's policies."],
      ["a response to Iran joining the World Trade Organization", "Iran is not a WTO member; this was unrelated."],
    ],
    answer: "B",
    explanation: "The protests show how participation can challenge legitimacy and how authoritarian regimes respond with repression.",
    countryIds: ["iran"],
  }),
  q({
    id: "cg3-07",
    topicId: "comp-civil-liberties-media",
    difficulty: "easy",
    concept: "Internet control",
    stem: "China's \"Great Firewall\" refers to",
    choices: [
      ["a program to reduce air pollution in Beijing", "The Great Firewall concerns internet control."],
      ["border fortifications in Xinjiang", "This is not what the term refers to."],
      ["a system of internet controls that blocks foreign websites and filters content", "Correct. It limits access to information and supports regime control of the media environment."],
      ["a trade barrier on foreign technology imports", "The term describes censorship, not trade policy."],
    ],
    answer: "C",
    explanation: "The Great Firewall, along with domestic censorship, helps the party shape the information citizens receive.",
    countryIds: ["china"],
  }),
  q({
    id: "cg3-08",
    topicId: "comp-civil-liberties-media",
    difficulty: "medium",
    concept: "Russia's foreign agents law",
    stem: "Russia's foreign agents laws have most directly affected civil liberties by",
    choices: [
      ["guaranteeing funding for independent journalists", "The laws have restricted, not supported, independent media."],
      ["requiring the election of regional governors", "The laws concern organizations and media, not elections."],
      ["expanding the independence of the Constitutional Court", "The laws are unrelated to judicial independence."],
      ["stigmatizing and restricting NGOs and journalists labeled as receiving foreign support", "Correct. Labeling and reporting requirements have been used to marginalize critics."],
    ],
    answer: "D",
    explanation: "Foreign agents designations impose burdens and stigma that have forced many organizations to close.",
    countryIds: ["russia"],
  }),
  q({
    id: "cg3-09",
    topicId: "comp-civil-liberties-media",
    difficulty: "hard",
    concept: "Press freedom in Mexico",
    stem: "Which of the following best explains why Mexico is considered dangerous for journalists despite legal protections for the press?",
    choices: [
      ["Violence by organized crime and threats from some local officials", "Correct. Journalists covering crime and corruption face serious risks."],
      ["A national law requiring all news to be approved by the president", "No such law exists in Mexico."],
      ["The government owns all television networks", "Mexico has privately owned media."],
      ["The Guardian Council censors publications", "The Guardian Council is an Iranian institution."],
    ],
    answer: "A",
    explanation: "Mexico illustrates how formal protections can coexist with dangerous conditions created by non-state actors and weak rule of law.",
    countryIds: ["mexico"],
  }),
  q({
    id: "cg3-10",
    topicId: "comp-cleavages",
    difficulty: "medium",
    concept: "Coinciding cleavages",
    stem: "In Nigeria, ethnic, religious, and regional divisions often align — for example, a largely Muslim, Hausa-Fulani north. These are best described as",
    choices: [
      ["cross-cutting cleavages", "Cross-cutting cleavages overlap across groups and tend to moderate conflict."],
      ["coinciding cleavages", "Correct. When divisions reinforce one another, conflict tends to intensify."],
      ["class cleavages", "The scenario describes ethnic, religious, and regional divisions."],
      ["generational cleavages", "Generational differences are not described."],
    ],
    answer: "B",
    explanation: "Coinciding cleavages contributed to the Biafran war and continue to shape Nigerian politics.",
    countryIds: ["nigeria"],
  }),
  q({
    id: "cg3-11",
    topicId: "comp-cleavages",
    difficulty: "medium",
    concept: "Federal character principle",
    stem: "Nigeria's federal character principle is designed to",
    choices: [
      ["require the president to be from the largest ethnic group", "The principle aims for broad representation, not dominance by one group."],
      ["establish sharia law in all states", "Sharia applies in some northern states; this is unrelated."],
      ["ensure that government appointments reflect the country's diversity", "Correct. It seeks to prevent any group from dominating public institutions."],
      ["prohibit political parties based on religion", "This is a separate rule; the federal character principle concerns appointments."],
    ],
    answer: "C",
    explanation: "Along with federalism and informal zoning, the federal character principle is a tool for managing Nigeria's cleavages.",
    countryIds: ["nigeria"],
  }),
  q({
    id: "cg3-12",
    topicId: "comp-cleavages",
    difficulty: "hard",
    concept: "Managing cleavages",
    stem: "The 1998 Good Friday Agreement addressed conflict in Northern Ireland primarily by",
    choices: [
      ["creating a power-sharing government and devolved assembly", "Correct. Power sharing gave both communities a role in government."],
      ["making Northern Ireland an independent state", "Northern Ireland remains part of the UK."],
      ["banning political parties associated with religious communities", "Parties representing both communities participate in government."],
      ["merging Northern Ireland with Scotland", "No such merger occurred."],
    ],
    answer: "A",
    explanation: "Power-sharing and devolution are institutional responses to deep cleavages — useful contrasts with repression-based approaches.",
    countryIds: ["uk"],
  }),
];
