import { bank } from "./helpers";

const q = bank("compgov", "compgov-u5");

export const compgovU5Questions = [
  q({
    id: "cg5-01",
    topicId: "comp-globalization",
    difficulty: "easy",
    concept: "Special economic zones",
    stem: "China's creation of special economic zones beginning in 1980 is best described as",
    choices: [
      ["a policy to limit foreign investment", "SEZs were designed to attract foreign investment."],
      ["a return to central planning", "SEZs introduced market-friendly rules."],
      ["targeted economic liberalization to attract foreign investment while maintaining party control", "Correct. SEZs allowed experimentation with markets under Communist Party rule."],
      ["a step toward multiparty democracy", "Economic reforms were not accompanied by political liberalization."],
    ],
    answer: "C",
    explanation: "SEZs like Shenzhen show China's state-guided approach to globalization.",
    countryIds: ["china"],
  }),
  q({
    id: "cg5-02",
    topicId: "comp-globalization",
    difficulty: "medium",
    concept: "Globalization and backlash in Mexico",
    stem: "The Zapatista uprising in Chiapas, which began on January 1, 1994, was in part a protest against",
    choices: [
      ["the implementation of NAFTA and its effects on Indigenous and rural communities", "Correct. The uprising began the day NAFTA took effect."],
      ["Mexico's transition to a parliamentary system", "Mexico remained presidential."],
      ["the 2024 judicial reform", "The uprising occurred three decades earlier."],
      ["the removal of fuel subsidies", "This describes Nigeria in 2023."],
    ],
    answer: "A",
    explanation: "The Zapatistas highlighted how globalization and neoliberal reforms created losers as well as winners.",
    countryIds: ["mexico"],
  }),
  q({
    id: "cg5-03",
    topicId: "comp-globalization",
    difficulty: "medium",
    concept: "Privatization in Russia",
    stem: "Which outcome is most associated with Russia's rapid privatization in the 1990s?",
    choices: [
      ["Broad, evenly distributed ownership of former state enterprises", "Ownership became highly concentrated."],
      ["The concentration of wealth among a small group of oligarchs", "Correct. Insider deals transferred major assets to a few individuals."],
      ["Russia's immediate entry into the European Union", "Russia has never been an EU member."],
      ["The creation of special economic zones modeled on China", "This does not describe Russia's 1990s reforms."],
    ],
    answer: "B",
    explanation: "\"Shock therapy\" privatization produced oligarchs; under Putin, the state reasserted control over key sectors like energy.",
    countryIds: ["russia"],
  }),
  q({
    id: "cg5-04",
    topicId: "comp-globalization",
    difficulty: "hard",
    concept: "Brexit",
    stem: "The United Kingdom's 2016 vote to leave the European Union is most often explained as a response to",
    choices: [
      ["pressure from the IMF to adopt structural adjustment", "The UK was not under IMF structural adjustment."],
      ["the collapse of the UK's parliamentary system", "Parliament continued to function."],
      ["a constitutional requirement to hold a referendum every decade", "No such requirement exists."],
      ["concerns about national sovereignty and immigration associated with globalization", "Correct. The Leave campaign emphasized \"taking back control.\""],
    ],
    answer: "D",
    explanation: "Brexit illustrates political backlash against aspects of globalization and supranational governance.",
    countryIds: ["uk"],
  }),
  q({
    id: "cg5-05",
    topicId: "comp-development",
    difficulty: "medium",
    concept: "Rentier states",
    stem: "Which of the following best describes a rentier state?",
    choices: [
      ["A state that relies heavily on revenue from natural resources rather than taxation of citizens", "Correct. Resource rents reduce the state's dependence on taxpayers."],
      ["A state that rents land to foreign governments", "This is not the meaning of rentier state."],
      ["A state that relies primarily on income taxes", "Heavy reliance on taxation is the opposite of rentierism."],
      ["A state with a highly diversified manufacturing economy", "Rentier states are typically dependent on a narrow resource base."],
    ],
    answer: "A",
    explanation: "Rentier states can weaken accountability because governments depend less on citizens' taxes.",
    countryIds: ["nigeria", "iran", "russia"],
  }),
  q({
    id: "cg5-06",
    topicId: "comp-development",
    difficulty: "hard",
    concept: "Development indicators",
    stimulus: {
      kind: "table",
      title: "Selected Development Indicators (hypothetical)",
      headers: ["Country", "GDP per capita (USD)", "Gini coefficient", "HDI"],
      rows: [
        ["Country P", "12,000", "0.30", "0.80"],
        ["Country Q", "12,500", "0.52", "0.71"],
        ["Country R", "3,000", "0.35", "0.55"],
      ],
      note: "Hypothetical data for practice.",
    },
    stem: "Based on the table, which conclusion is best supported?",
    choices: [
      ["Country Q has the most equal distribution of income.", "Q has the highest Gini, indicating the most inequality."],
      ["Country R is the most developed because it has the lowest GDP per capita.", "Lower GDP per capita and HDI indicate less development."],
      ["Countries P and Q have similar average incomes, but Q has much greater inequality and lower human development.", "Correct. Similar GDP per capita masks differences in inequality and HDI."],
      ["GDP per capita alone fully captures differences in development among these countries.", "P and Q show that GDP per capita misses important differences."],
    ],
    answer: "C",
    explanation: "Using multiple indicators reveals what averages hide — a key skill for Quantitative Analysis questions.",
  }),
  q({
    id: "cg5-07",
    topicId: "comp-development",
    difficulty: "medium",
    concept: "Nigeria's economic reforms",
    stem: "In 2023, Nigeria's government removed a long-standing fuel subsidy. The most likely short-term political consequence was",
    choices: [
      ["a sharp drop in the price of fuel", "Removing a subsidy raised fuel prices."],
      ["increased cost-of-living pressures and public discontent", "Correct. Fuel and transport costs rose sharply."],
      ["the immediate end of Nigeria's dependence on oil revenue", "Subsidy removal didn't end oil dependence."],
      ["a transition from a presidential to a parliamentary system", "Economic reform didn't change the system of government."],
    ],
    answer: "B",
    explanation: "Reforms that improve public finances can be politically costly when they raise living costs — a recurring tension in rentier economies.",
    countryIds: ["nigeria"],
  }),
  q({
    id: "cg5-08",
    topicId: "comp-policy-challenges",
    difficulty: "medium",
    concept: "China's population policy",
    stem: "Which sequence correctly describes the evolution of China's population policy?",
    choices: [
      ["Three-child policy, then two-child policy, then one-child policy", "This reverses the order."],
      ["One-child policy throughout the present", "The one-child policy ended in 2015."],
      ["No population policy until a one-child policy in 2021", "The one-child policy began around 1980."],
      ["One-child policy, then a two-child policy (2016), then a three-child policy (2021)", "Correct. The government relaxed limits as concerns about aging grew."],
    ],
    answer: "D",
    explanation: "China's shift reflects concerns about an aging population, a shrinking workforce, and gender imbalance.",
    countryIds: ["china"],
  }),
  q({
    id: "cg5-09",
    topicId: "comp-policy-challenges",
    difficulty: "medium",
    concept: "Conditional cash transfers",
    stem: "Mexico's Progresa/Oportunidades/Prospera program provided cash to low-income families on the condition that they",
    choices: [
      ["kept children in school and attended health checkups", "Correct. Conditions linked payments to investments in education and health."],
      ["joined the governing party", "The program's conditions concerned education and health, not party membership."],
      ["moved to urban areas", "The program did not require migration."],
      ["purchased goods from state-owned enterprises", "No such condition existed."],
    ],
    answer: "A",
    explanation: "The program became a global model for conditional cash transfers before being replaced in 2019.",
    countryIds: ["mexico"],
  }),
  q({
    id: "cg5-10",
    topicId: "comp-policy-challenges",
    difficulty: "hard",
    concept: "Hukou system",
    stem: "China's hukou system creates a policy challenge primarily because it",
    choices: [
      ["requires all citizens to live in rural areas", "Hundreds of millions of Chinese live in cities."],
      ["limits rural migrants' access to public services in the cities where they work", "Correct. Registration status ties access to education and health care to a person's registered residence."],
      ["gives urban residents the right to elect provincial leaders", "Hukou concerns household registration, not elections."],
      ["prohibits families from having more than one child", "That was the one-child policy."],
    ],
    answer: "B",
    explanation: "The hukou system contributes to inequality between urban residents and rural migrants — a major social-policy issue.",
    countryIds: ["china"],
  }),
  q({
    id: "cg5-11",
    topicId: "comp-policy-challenges",
    difficulty: "medium",
    concept: "Policy and public response",
    stem: "Russia's 2018 decision to raise the retirement age led to protests and a drop in government approval. This case best illustrates that",
    choices: [
      ["authoritarian regimes never adjust policies in response to public opinion", "Putin softened the reform, showing some responsiveness."],
      ["Russia's legislature regularly blocks presidential proposals", "The Duma passed the reform."],
      ["even authoritarian regimes can face pressure to modify unpopular social policies", "Correct. The government adjusted the reform after public backlash."],
      ["pension policy is set by regional governments in Russia", "Pension policy is set nationally."],
    ],
    answer: "C",
    explanation: "Authoritarian governments monitor public opinion and sometimes make concessions to protect legitimacy.",
    countryIds: ["russia"],
  }),
];
