import { bank } from "./helpers";

const q = bank("compgov", "compgov-u2");

export const compgovU2Questions = [
  q({
    id: "cg2-01",
    topicId: "comp-executive-systems",
    difficulty: "easy",
    concept: "Parliamentary systems",
    stem: "Which feature is characteristic of a parliamentary system but not a presidential system?",
    choices: [
      ["A directly elected head of government with a fixed term", "This is characteristic of presidential systems."],
      ["An independent judiciary", "Independent judiciaries exist in both types."],
      ["A bicameral legislature", "Both types can have bicameral legislatures."],
      ["A government that can be removed by a legislative vote of no confidence", "Correct. The executive depends on the confidence of the legislature."],
    ],
    answer: "D",
    explanation: "In parliamentary systems, executive and legislative power are fused, and the government must retain majority support.",
  }),
  q({
    id: "cg2-02",
    topicId: "comp-executive-systems",
    difficulty: "medium",
    concept: "Semi-presidential systems",
    stem: "Which course country has a semi-presidential system, with a directly elected president and a prime minister who requires legislative approval?",
    choices: [
      ["Mexico", "Mexico is presidential; there is no prime minister."],
      ["Russia", "Correct. Russia's president appoints the prime minister with State Duma approval."],
      ["Nigeria", "Nigeria is presidential."],
      ["United Kingdom", "The UK is parliamentary; the monarch is not elected."],
    ],
    answer: "B",
    explanation: "Russia's structure is semi-presidential, but in practice the president dominates the prime minister and government.",
    countryIds: ["russia"],
  }),
  q({
    id: "cg2-03",
    topicId: "comp-executive-systems",
    difficulty: "medium",
    concept: "Head of state vs. head of government",
    stem: "In the United Kingdom, the head of state and head of government are, respectively,",
    choices: [
      ["the monarch and the prime minister", "Correct. The monarch has a largely ceremonial role; the prime minister leads the government."],
      ["the prime minister and the monarch", "This reverses the roles."],
      ["the Speaker of the House of Commons and the prime minister", "The Speaker presides over the Commons."],
      ["the prime minister and the Lord Chancellor", "The Lord Chancellor is a cabinet minister, not head of government."],
    ],
    answer: "A",
    explanation: "The UK separates ceremonial and political executive roles, unlike presidential systems where one person fills both.",
    countryIds: ["uk"],
  }),
  q({
    id: "cg2-04",
    topicId: "comp-executives",
    difficulty: "easy",
    concept: "Term limits in Mexico",
    stem: "Mexico's president is limited to",
    choices: [
      ["two four-year terms", "This describes Nigeria's presidential term limits."],
      ["no term limits", "Mexico has strict limits."],
      ["a single six-year term with no reelection", "Correct. The sexenio reflects a historic rejection of the Díaz dictatorship."],
      ["two six-year terms", "Mexican presidents cannot be reelected."],
    ],
    answer: "C",
    explanation: "Mexico's single-term rule is one of the strictest executive term limits in the world.",
    countryIds: ["mexico"],
  }),
  q({
    id: "cg2-05",
    topicId: "comp-executives",
    difficulty: "medium",
    concept: "Term limits in China",
    stem: "The 2018 removal of presidential term limits in China is most often interpreted as evidence of",
    choices: [
      ["the growing independence of the National People's Congress", "The NPC approved the change with near-unanimous support."],
      ["the consolidation of power by the top leader", "Correct. The change allowed Xi Jinping to remain president beyond two terms."],
      ["a transition toward democracy", "Removing limits on leadership tenure is generally seen as the opposite of democratization."],
      ["the decline of the Chinese Communist Party", "The change strengthened party leadership under Xi."],
    ],
    answer: "B",
    explanation: "Removing term limits reduced an institutional constraint on the top leader, signaling personalization of power.",
    countryIds: ["china"],
  }),
  q({
    id: "cg2-06",
    topicId: "comp-executives",
    difficulty: "medium",
    concept: "Supreme Leader selection",
    stem: "Iran's Supreme Leader is chosen by",
    choices: [
      ["a direct popular vote", "The Supreme Leader is not directly elected."],
      ["the Guardian Council", "The Guardian Council vets candidates and legislation; it does not choose the Supreme Leader."],
      ["the Majles", "The legislature does not select the Supreme Leader."],
      ["the Assembly of Experts", "Correct. This elected body of senior clerics selects and can in principle remove the Supreme Leader."],
    ],
    answer: "D",
    explanation: "The Assembly of Experts is elected by voters, but candidates are vetted by the Guardian Council — a layered system that limits popular control.",
    countryIds: ["iran"],
  }),
  q({
    id: "cg2-07",
    topicId: "comp-executives",
    difficulty: "hard",
    concept: "Formal vs. informal executive power",
    stem: "Which statement best explains why China's president is considered powerful?",
    choices: [
      ["The officeholder is also General Secretary of the Communist Party and chair of the Central Military Commission.", "Correct. Real power comes from party and military positions held by the same person."],
      ["The constitution gives the president unlimited decree power.", "The presidency itself has limited formal powers."],
      ["The president is directly elected by the people.", "The NPC elects the president."],
      ["The president appoints all members of the National People's Congress.", "NPC deputies are indirectly elected by lower-level congresses."],
    ],
    answer: "A",
    explanation: "In China, state offices matter because of the party positions held by the same leaders.",
    countryIds: ["china"],
  }),
  q({
    id: "cg2-08",
    topicId: "comp-legislatures",
    difficulty: "medium",
    concept: "House of Lords",
    stem: "Which statement accurately describes the power of the UK House of Lords?",
    choices: [
      ["It can permanently veto any legislation passed by the House of Commons.", "The Parliament Acts limit the Lords to delaying most legislation."],
      ["It can remove the prime minister through a vote of no confidence.", "Confidence votes take place in the Commons."],
      ["It can revise and delay most legislation, but the Commons can ultimately prevail.", "Correct. The elected Commons is dominant."],
      ["Its members are elected by proportional representation.", "Members of the Lords are appointed or sit by hereditary or religious position."],
    ],
    answer: "C",
    explanation: "The House of Lords is a revising chamber whose power is limited by the Parliament Acts.",
    countryIds: ["uk"],
  }),
  q({
    id: "cg2-09",
    topicId: "comp-legislatures",
    difficulty: "medium",
    concept: "National People's Congress",
    stem: "Which statement best describes China's National People's Congress?",
    choices: [
      ["It frequently rejects proposals from the Communist Party leadership.", "The NPC rarely rejects party decisions."],
      ["It is formally the highest organ of state power but largely approves decisions made by party leaders.", "Correct. Its formal powers far exceed its practical independence."],
      ["Its members are directly elected in competitive national elections.", "Deputies are indirectly elected."],
      ["It can remove the General Secretary of the Communist Party.", "The General Secretary is a party position selected within the party."],
    ],
    answer: "B",
    explanation: "The NPC illustrates the gap between formal constitutional power and actual practice in authoritarian regimes.",
    countryIds: ["china"],
  }),
  q({
    id: "cg2-10",
    topicId: "comp-legislatures",
    difficulty: "hard",
    concept: "Guardian Council",
    stem: "Iran's Majles passes a bill, but the bill does not become law. Which is the most likely explanation?",
    choices: [
      ["The House of Lords delayed it.", "The House of Lords is part of the UK Parliament."],
      ["The Assembly of Experts vetoed it.", "The Assembly of Experts selects the Supreme Leader; it does not review legislation."],
      ["A majority of provincial governors rejected it.", "Iran is unitary; governors don't veto national laws."],
      ["The Guardian Council found it incompatible with Islamic law or the constitution.", "Correct. The Guardian Council reviews legislation passed by the Majles."],
    ],
    answer: "D",
    explanation: "The Guardian Council limits the Majles's independence by reviewing legislation and vetting candidates.",
    countryIds: ["iran"],
  }),
  q({
    id: "cg2-11",
    topicId: "comp-judiciaries",
    difficulty: "medium",
    concept: "Parliamentary sovereignty",
    stem: "Why can't the UK Supreme Court strike down an act of Parliament?",
    choices: [
      ["Because of the principle of parliamentary sovereignty", "Correct. Parliament is the supreme legal authority in the UK."],
      ["Because the court's judges are appointed by the monarch", "The appointment process isn't what limits the court's power over statutes."],
      ["Because the UK has a codified constitution that forbids judicial review", "The UK constitution is uncodified."],
      ["Because the court is part of the House of Lords", "Since 2009, the Supreme Court has been separate from the House of Lords."],
    ],
    answer: "A",
    explanation: "UK courts can issue declarations of incompatibility under the Human Rights Act but cannot invalidate statutes.",
    countryIds: ["uk"],
  }),
  q({
    id: "cg2-12",
    topicId: "comp-judiciaries",
    difficulty: "medium",
    concept: "Mexico's judicial reform",
    stem: "Mexico's 2024 judicial reform is significant primarily because it",
    choices: [
      ["abolished the Supreme Court", "The reform restructured the Court rather than abolishing it."],
      ["gave the president power to appoint all judges without Senate approval", "The reform introduced elections, not unilateral presidential appointment."],
      ["introduced popular elections for judges, including Supreme Court justices", "Correct. Supporters cited anti-corruption goals; critics warned about judicial independence."],
      ["adopted sharia law in several states", "This describes northern Nigeria, not Mexico."],
    ],
    answer: "C",
    explanation: "Judicial elections were first held in 2025. The debate centers on accountability versus independence.",
    countryIds: ["mexico"],
  }),
  q({
    id: "cg2-13",
    topicId: "comp-judiciaries",
    difficulty: "hard",
    concept: "Measuring judicial independence",
    stem: "Which of the following would provide the strongest evidence of judicial independence in a country?",
    choices: [
      ["The constitution lists the judiciary as a separate branch.", "Formal provisions don't guarantee independence in practice."],
      ["Judges are required to be members of the ruling party.", "Party membership requirements undermine independence."],
      ["Courts hear large numbers of civil cases each year.", "Caseload says nothing about independence from political pressure."],
      ["A high court rules against the executive in a politically important case, and the executive complies.", "Correct. Ruling against the powerful — and being obeyed — demonstrates real independence."],
    ],
    answer: "D",
    explanation: "Independence is best measured by behavior: willingness to rule against those in power and compliance with those rulings.",
  }),
];
