import { bank } from "./helpers";

const q = bank("compgov", "compgov-u4");

export const compgovU4Questions = [
  q({
    id: "cg4-01",
    topicId: "comp-electoral-systems",
    difficulty: "hard",
    concept: "SMD disproportionality",
    stimulus: {
      kind: "table",
      title: "UK General Election, 2024 — Vote Share vs. Seats (rounded)",
      headers: ["Party", "Vote share", "Seats (of 650)"],
      rows: [
        ["Labour", "34%", "411"],
        ["Conservative", "24%", "121"],
        ["Reform UK", "14%", "5"],
        ["Liberal Democrats", "12%", "72"],
        ["Green", "7%", "4"],
      ],
      source: "UK House of Commons Library, 2024 general election results.",
      note: "Figures rounded. Seat totals exclude the Speaker.",
    },
    stem: "Which statement best explains the pattern in the table?",
    choices: [
      ["Proportional representation gave each party seats in proportion to its votes.", "The UK uses SMD plurality, and seats are clearly not proportional to votes."],
      ["Single-member district plurality rules rewarded parties with concentrated support and penalized those with dispersed support.", "Correct. The Liberal Democrats' concentrated support won far more seats than Reform UK's larger but dispersed vote."],
      ["A 5% threshold prevented Reform UK from winning seats.", "The UK has no national threshold; Reform UK won 5 seats."],
      ["The House of Lords redistributed seats after the election.", "The Lords has no role in allocating Commons seats."],
    ],
    answer: "B",
    explanation: "Under first past the post, geographic concentration matters as much as total votes. That's why Reform UK won far fewer seats than the Liberal Democrats despite a slightly larger vote share.",
    countryIds: ["uk"],
  }),
  q({
    id: "cg4-02",
    topicId: "comp-electoral-systems",
    difficulty: "medium",
    concept: "Mixed electoral systems",
    stem: "Mexico's Chamber of Deputies uses a mixed electoral system, which means that",
    choices: [
      ["some members are elected in single-member districts and others through proportional representation", "Correct. 300 seats come from districts and 200 from PR lists."],
      ["half the members are elected and half are appointed by the president", "All deputies are elected."],
      ["voters choose between a presidential and parliamentary system", "Mixed refers to the electoral formula, not the system of government."],
      ["members are elected by state legislatures", "Deputies are elected by voters."],
    ],
    answer: "A",
    explanation: "Mixed systems balance local representation with proportionality. Russia's State Duma also uses a mixed system.",
    countryIds: ["mexico"],
  }),
  q({
    id: "cg4-03",
    topicId: "comp-electoral-systems",
    difficulty: "medium",
    concept: "Nigeria's presidential election rules",
    stem: "Nigeria requires a winning presidential candidate to receive at least 25% of the vote in two-thirds of the states. The primary purpose of this rule is to",
    choices: [
      ["guarantee that the president comes from the ruling party", "The rule concerns geographic distribution, not party."],
      ["reduce voter turnout in the north", "The rule is unrelated to turnout."],
      ["ensure the winner has broad support across regions and ethnic groups", "Correct. It discourages candidates who appeal only to one region."],
      ["allow the National Assembly to choose the president", "The rule applies to a direct popular election."],
    ],
    answer: "C",
    explanation: "The distribution requirement is an institutional response to Nigeria's regional and ethnic cleavages.",
    countryIds: ["nigeria"],
  }),
  q({
    id: "cg4-04",
    topicId: "comp-electoral-systems",
    difficulty: "hard",
    concept: "Electoral thresholds",
    stem: "Russia's State Duma elections include a 5% threshold for proportional representation seats. The most likely effect of this threshold is to",
    choices: [
      ["increase the number of small parties in the Duma", "Thresholds reduce, not increase, small-party representation."],
      ["guarantee opposition parties a majority", "Thresholds don't guarantee majorities to any party."],
      ["require all candidates to win 5% of the vote in every region", "The threshold applies to national party-list votes."],
      ["prevent small parties from winning PR seats, benefiting larger parties", "Correct. Votes for parties below the threshold don't translate into PR seats."],
    ],
    answer: "D",
    explanation: "Thresholds limit fragmentation. In Russia, they have also helped the dominant party and the \"systemic opposition\" retain their positions.",
    countryIds: ["russia"],
  }),
  q({
    id: "cg4-05",
    topicId: "comp-party-systems",
    difficulty: "medium",
    concept: "China's party system",
    stem: "Which statement most accurately describes China's party system?",
    choices: [
      ["Only the Communist Party is legal, and no other parties exist.", "Eight minor parties exist legally."],
      ["Several minor parties exist but accept the Communist Party's leadership.", "Correct. China is effectively a one-party system despite the existence of minor parties."],
      ["Two major parties alternate in power.", "The Communist Party has held power continuously since 1949."],
      ["Parties compete in national legislative elections under proportional representation.", "There are no competitive national elections."],
    ],
    answer: "B",
    explanation: "The minor \"democratic parties\" participate in consultative bodies but do not challenge Communist Party rule.",
    countryIds: ["china"],
  }),
  q({
    id: "cg4-06",
    topicId: "comp-party-systems",
    difficulty: "medium",
    concept: "Dominant-party systems",
    stem: "Russia's party system is best described as",
    choices: [
      ["a dominant-party system in which United Russia consistently controls the legislature", "Correct. Other parties hold seats but rarely challenge the Kremlin."],
      ["a two-party system", "Several parties hold Duma seats, but one dominates."],
      ["a competitive multiparty system with frequent alternation in power", "Power has not alternated since the early 2000s."],
      ["a one-party system in which other parties are illegal", "Other parties are legal and hold seats."],
    ],
    answer: "A",
    explanation: "Dominant-party systems allow multiple parties but lack meaningful alternation in power.",
    countryIds: ["russia"],
  }),
  q({
    id: "cg4-07",
    topicId: "comp-party-systems",
    difficulty: "hard",
    concept: "Party change in Mexico",
    stem: "Which development best describes change in Mexico's party system since 2000?",
    choices: [
      ["The PRI regained permanent dominance after 2000.", "The PRI won the presidency once more (2012) but has since declined sharply."],
      ["Mexico adopted a one-party system under MORENA.", "Multiple parties continue to compete; MORENA's strength has sparked debate but not a one-party system."],
      ["MORENA emerged as the dominant force, winning the presidency in 2018 and 2024 as the PRI and PAN weakened.", "Correct. This reshaped a party system that had been dominated by the PRI and PAN."],
      ["The PAN has controlled the presidency continuously since 2000.", "The PAN held the presidency from 2000 to 2012."],
    ],
    answer: "C",
    explanation: "Mexico's party system moved from PRI dominance to competition among PRI, PAN, and PRD, and then to MORENA's rise.",
    countryIds: ["mexico"],
  }),
  q({
    id: "cg4-08",
    topicId: "comp-civil-society",
    difficulty: "medium",
    concept: "Corporatism",
    stem: "Under the PRI, Mexican labor and peasant organizations were incorporated into the ruling party in exchange for benefits. This arrangement is an example of",
    choices: [
      ["pluralism", "Pluralism features many independent groups competing for influence."],
      ["federalism", "Federalism divides power between levels of government."],
      ["devolution", "Devolution transfers power to regional governments."],
      ["corporatism", "Correct. The state recognized and incorporated specific groups to represent sectors."],
    ],
    answer: "D",
    explanation: "Corporatism channels interest representation through a limited number of state-recognized organizations, often linked to patronage.",
    countryIds: ["mexico"],
  }),
  q({
    id: "cg4-09",
    topicId: "comp-civil-society",
    difficulty: "easy",
    concept: "Pluralism",
    stem: "In the United Kingdom, business associations, trade unions, and thousands of advocacy groups compete to influence Parliament and government ministries. This is best described as",
    choices: [
      ["pluralism", "Correct. Many independent groups compete for influence."],
      ["state corporatism", "State corporatism involves groups created or controlled by the state."],
      ["clientelism", "Clientelism involves exchanging benefits for political support."],
      ["rentierism", "Rentierism describes states dependent on resource revenue."],
    ],
    answer: "A",
    explanation: "Pluralist civil society features independent groups competing openly — characteristic of the UK.",
    countryIds: ["uk"],
  }),
  q({
    id: "cg4-10",
    topicId: "comp-civil-society",
    difficulty: "hard",
    concept: "Bonyads",
    stem: "Iran's bonyads are best described as",
    choices: [
      ["independent human rights organizations critical of the regime", "Bonyads are closely tied to the regime."],
      ["large, religiously affiliated foundations that control significant economic assets and are linked to the regime's elite", "Correct. They blur the line between the state, religion, and the economy."],
      ["elected local councils", "Bonyads are not elected bodies."],
      ["opposition political parties", "Bonyads are economic foundations, not parties."],
    ],
    answer: "B",
    explanation: "Bonyads illustrate how authoritarian regimes can use quasi-state organizations to distribute resources and reward supporters.",
    countryIds: ["iran"],
  }),
];
