import { bank } from "./helpers";

const q = bank("compgov", "compgov-u1");

export const compgovU1Questions = [
  q({
    id: "cg1-01",
    topicId: "comp-comparative-method",
    difficulty: "easy",
    concept: "State vs. nation",
    stem: "The United Kingdom includes England, Scotland, Wales, and Northern Ireland, each with distinct identities. This best illustrates which concept?",
    choices: [
      ["A single state containing multiple nations", "Correct. The UK is one sovereign state whose population includes several national identities."],
      ["A confederation of sovereign states", "England, Scotland, Wales, and Northern Ireland are not sovereign states."],
      ["A federal system", "The UK is unitary, with devolved governments."],
      ["A regime change", "Nothing in the scenario involves changing the fundamental rules of the political system."],
    ],
    answer: "A",
    explanation: "A state is a sovereign political-legal entity; a nation is a people with shared identity. The UK is a multinational state.",
    countryIds: ["uk"],
  }),
  q({
    id: "cg1-02",
    topicId: "comp-comparative-method",
    difficulty: "medium",
    concept: "Normative vs. empirical",
    stem: "Which of the following is a normative statement?",
    choices: [
      ["Voter turnout in Iran's 2024 legislative elections was lower than in previous legislative elections.", "This can be checked with data — an empirical statement."],
      ["Mexico's Chamber of Deputies has 500 members.", "This is a verifiable fact — an empirical statement."],
      ["Nigeria should adopt a parliamentary system to reduce ethnic conflict.", "Correct. \"Should\" signals a value judgment about what ought to be."],
      ["China's National People's Congress meets annually.", "This is a verifiable fact — an empirical statement."],
    ],
    answer: "C",
    explanation: "Normative statements express values or preferences; empirical statements can be tested against evidence.",
  }),
  q({
    id: "cg1-03",
    topicId: "comp-comparative-method",
    difficulty: "hard",
    concept: "Correlation vs. causation",
    stimulus: {
      kind: "table",
      title: "GDP per Capita and Democracy Score in Five Countries (hypothetical)",
      headers: ["Country", "GDP per capita (USD)", "Democracy score (0–10)"],
      rows: [
        ["Country V", "4,000", "3.1"],
        ["Country W", "9,500", "4.8"],
        ["Country X", "18,000", "6.2"],
        ["Country Y", "31,000", "7.9"],
        ["Country Z", "45,000", "8.6"],
      ],
      note: "Hypothetical data for practice.",
    },
    stem: "Which conclusion is best supported by the data?",
    choices: [
      ["Increasing GDP per capita causes countries to become more democratic.", "The data shows association only; it can't establish causation."],
      ["In these five countries, higher GDP per capita is associated with higher democracy scores.", "Correct. The data shows a positive correlation among these cases."],
      ["Democracy causes economic growth in every country.", "The data can't establish causation or generalize to every country."],
      ["Country V will become more democratic as its economy grows.", "The table provides no data over time, so it can't support predictions about change."],
    ],
    answer: "B",
    explanation: "Comparative questions often test whether you can distinguish correlation from causation. A cross-sectional pattern doesn't show which factor, if either, causes the other.",
  }),
  q({
    id: "cg1-04",
    topicId: "comp-democracy-authoritarianism",
    difficulty: "medium",
    concept: "Indicators of authoritarianism",
    stem: "Which of the following is the strongest indicator that a regime is authoritarian rather than democratic?",
    choices: [
      ["The legislature is bicameral.", "Bicameralism exists in democracies and authoritarian regimes alike."],
      ["The head of state is a hereditary monarch.", "Constitutional monarchies such as the UK are democratic."],
      ["The government collects most of its revenue from oil exports.", "Resource dependence is a risk factor, not a defining feature of regime type."],
      ["An unelected body routinely disqualifies candidates who would challenge the ruling elite.", "Correct. Restricting who can compete prevents elections from being free and fair."],
    ],
    answer: "D",
    explanation: "Democracy requires competitive elections. Iran's Guardian Council, which vets and disqualifies candidates, is a classic example of limits on competition.",
    countryIds: ["iran"],
  }),
  q({
    id: "cg1-05",
    topicId: "comp-democracy-authoritarianism",
    difficulty: "medium",
    concept: "Democratization in Mexico",
    stem: "The 2000 presidential election in Mexico is significant because",
    choices: [
      ["it was the first time an opposition candidate won the presidency, ending decades of PRI dominance", "Correct. Vicente Fox of the PAN won, marking a key step in Mexico's democratization."],
      ["it was the first election after Mexico adopted a parliamentary system", "Mexico has a presidential system."],
      ["it was the first election in which women could vote", "Women gained the vote in federal elections in the 1950s."],
      ["MORENA won its first national election", "MORENA was founded in the 2010s and won the presidency in 2018."],
    ],
    answer: "A",
    explanation: "Electoral reforms and an independent electoral institute enabled real competition, culminating in the PAN's victory in 2000.",
    countryIds: ["mexico"],
  }),
  q({
    id: "cg1-06",
    topicId: "comp-democracy-authoritarianism",
    difficulty: "hard",
    concept: "Democratic consolidation",
    stem: "Nigeria's 2015 presidential election is often cited as evidence of democratic progress because",
    choices: [
      ["the military formally returned power to civilians for the first time", "The transition from military to civilian rule occurred in 1999."],
      ["an incumbent president lost to an opposition candidate and peacefully transferred power", "Correct. Goodluck Jonathan conceded to Muhammadu Buhari."],
      ["Nigeria adopted proportional representation for its legislature", "Nigeria uses single-member districts."],
      ["the president was chosen by the National Assembly", "Nigeria's president is directly elected."],
    ],
    answer: "B",
    explanation: "Peaceful alternation in power — especially an incumbent accepting defeat — is a key indicator of democratic consolidation.",
    countryIds: ["nigeria"],
  }),
  q({
    id: "cg1-07",
    topicId: "comp-legitimacy",
    difficulty: "medium",
    concept: "Performance legitimacy",
    stem: "The Chinese Communist Party's emphasis on rapid economic growth and rising living standards as justification for its rule is an example of",
    choices: [
      ["traditional legitimacy", "Traditional legitimacy rests on custom, such as hereditary monarchy."],
      ["rational-legal legitimacy based on competitive elections", "China does not hold competitive national elections."],
      ["performance legitimacy", "Correct. The party ties its right to rule to delivering economic results."],
      ["charismatic legitimacy", "The emphasis here is on results, not on a leader's personal appeal."],
    ],
    answer: "C",
    explanation: "Performance legitimacy depends on delivering growth and stability — which can create vulnerability if performance falters.",
    countryIds: ["china"],
  }),
  q({
    id: "cg1-08",
    topicId: "comp-legitimacy",
    difficulty: "medium",
    concept: "Religious legitimacy",
    stem: "The authority of Iran's Supreme Leader is based primarily on",
    choices: [
      ["victory in a direct national election", "The Supreme Leader is chosen by the Assembly of Experts, not directly elected."],
      ["hereditary succession", "Iran abolished its monarchy in 1979."],
      ["appointment by the president", "The president does not appoint the Supreme Leader."],
      ["religious legitimacy under the principle of guardianship of the Islamic jurist", "Correct. Velayat-e faqih gives a senior cleric ultimate authority."],
    ],
    answer: "D",
    explanation: "Iran's regime rests on velayat-e faqih — the idea that a qualified Islamic jurist should guide the state.",
    countryIds: ["iran"],
  }),
  q({
    id: "cg1-09",
    topicId: "comp-legitimacy",
    difficulty: "hard",
    concept: "Measuring legitimacy",
    stimulus: {
      kind: "bar",
      title: "Reported Turnout in Iranian Legislative Elections (approximate)",
      unit: "%",
      series: [
        { label: "2012", value: 64 },
        { label: "2016", value: 62 },
        { label: "2020", value: 42 },
        { label: "2024", value: 41 },
      ],
      source: "Figures as reported by Iran's Interior Ministry; rounded.",
      note: "Rounded for practice. Always verify figures used in your own work.",
    },
    stem: "The trend in the chart is most often used by analysts as evidence of",
    choices: [
      ["declining public confidence in the regime's electoral institutions", "Correct. Falling turnout is widely interpreted as a sign of disillusionment, though it is one indicator among several."],
      ["the introduction of compulsory voting", "Compulsory voting would increase, not decrease, turnout."],
      ["a shift from a parliamentary to a presidential system", "Iran's institutional structure did not change in this period."],
      ["increasing competitiveness of Iranian elections", "Growing candidate disqualifications have made elections less competitive."],
    ],
    answer: "A",
    explanation: "Turnout is an imperfect but frequently cited measure of legitimacy. Strong answers note both the trend and the limitation of using one indicator.",
    countryIds: ["iran"],
  }),
  q({
    id: "cg1-10",
    topicId: "comp-federal-unitary",
    difficulty: "medium",
    concept: "Devolution",
    stem: "Which of the following best describes the United Kingdom's system of government after devolution?",
    choices: [
      ["A federal system in which Scotland, Wales, and Northern Ireland have constitutionally guaranteed sovereignty", "Devolved powers are granted by Parliament, not constitutionally guaranteed."],
      ["A confederation in which regional governments can veto national laws", "Regional governments cannot veto Westminster legislation."],
      ["A unitary system in which Parliament has granted significant powers to regional governments", "Correct. Parliament remains sovereign even as it devolves authority."],
      ["A unitary system with no regional legislatures", "Scotland, Wales, and Northern Ireland have legislatures."],
    ],
    answer: "C",
    explanation: "Devolution transfers power without creating federalism: Westminster could, in principle, alter or reclaim devolved powers.",
    countryIds: ["uk"],
  }),
  q({
    id: "cg1-11",
    topicId: "comp-federal-unitary",
    difficulty: "medium",
    concept: "Recentralization",
    stem: "Since 2000, the Russian central government has most often",
    choices: [
      ["recentralized power by increasing federal control over regional governments", "Correct. The Kremlin created federal districts and gained influence over regional leadership."],
      ["devolved significant new powers to ethnic republics", "The trend has been toward centralization, not devolution."],
      ["abolished its federal structure and become a unitary state", "Russia remains formally federal."],
      ["allowed regions to conduct independent foreign policy", "Foreign policy is controlled by the central government."],
    ],
    answer: "A",
    explanation: "Russia is formally federal, but recentralization has concentrated power in Moscow — an example of formal structure differing from practice.",
    countryIds: ["russia"],
  }),
  q({
    id: "cg1-12",
    topicId: "comp-federal-unitary",
    difficulty: "easy",
    concept: "Federal systems in the course",
    stem: "Which group includes only course countries with federal systems?",
    choices: [
      ["United Kingdom, China, Iran", "These are unitary states."],
      ["Mexico, Nigeria, Russia", "Correct. All three constitutionally divide power between national and regional governments."],
      ["China, Mexico, United Kingdom", "China and the UK are unitary."],
      ["Iran, Nigeria, Russia", "Iran is unitary."],
    ],
    answer: "B",
    explanation: "Federal: Mexico, Nigeria, Russia. Unitary: the UK (with devolution), China, and Iran.",
  }),
];
