import { bank } from "./helpers";

const q = bank("usgov", "usgov-u5");

export const usgovU5Questions = [
  q({
    id: "us5-01",
    topicId: "usgov-voting-turnout",
    difficulty: "easy",
    concept: "Voting amendments",
    stem: "Which constitutional amendment lowered the voting age to 18?",
    choices: [
      ["Fifteenth Amendment", "The Fifteenth Amendment prohibits denying the vote based on race."],
      ["Nineteenth Amendment", "The Nineteenth Amendment prohibits denying the vote based on sex."],
      ["Twenty-Fourth Amendment", "The Twenty-Fourth Amendment bans poll taxes in federal elections."],
      ["Twenty-Sixth Amendment", "Correct. Ratified in 1971, it lowered the voting age to 18."],
    ],
    answer: "D",
    explanation: "The Twenty-Sixth Amendment was ratified during the Vietnam War era, amid arguments that those old enough to be drafted should be able to vote.",
  }),
  q({
    id: "us5-02",
    topicId: "usgov-voting-turnout",
    difficulty: "medium",
    concept: "Retrospective voting",
    stem: "A voter decides to vote against the incumbent president because unemployment rose during the president's term. This voter is engaging in",
    choices: [
      ["retrospective voting", "Correct. The voter is judging past performance."],
      ["prospective voting", "Prospective voting looks at what candidates promise to do in the future."],
      ["party-line voting", "Nothing indicates the decision was based on party loyalty."],
      ["rational choice voting based on a campaign promise", "The decision relies on past outcomes, not promises."],
    ],
    answer: "A",
    explanation: "Retrospective voters reward or punish incumbents based on their record, especially the economy.",
  }),
  q({
    id: "us5-03",
    topicId: "usgov-voting-turnout",
    difficulty: "hard",
    concept: "Turnout patterns",
    stimulus: {
      kind: "table",
      title: "Voter Turnout by Age Group (hypothetical)",
      headers: ["Age group", "Presidential election", "Midterm election"],
      rows: [
        ["18–29", "50%", "28%"],
        ["30–44", "60%", "40%"],
        ["45–64", "68%", "54%"],
        ["65+", "74%", "64%"],
      ],
      note: "Hypothetical data for practice, modeled on commonly observed patterns.",
    },
    stem: "Which conclusion is best supported by the data?",
    choices: [
      ["Young voters turn out at higher rates in midterm elections than in presidential elections.", "Young voters' turnout drops from 50% to 28% in midterms."],
      ["Turnout increases with age in both types of elections, and the drop-off from presidential to midterm elections is largest among the youngest voters.", "Correct. Turnout rises with age, and the 22-point drop for ages 18–29 is the largest."],
      ["Turnout is identical across age groups in presidential elections.", "Presidential turnout ranges from 50% to 74%."],
      ["The oldest voters show the largest decline in midterm turnout.", "The oldest group has the smallest decline (10 points)."],
    ],
    answer: "B",
    explanation: "Quantitative questions reward precise comparisons: identify the trend (turnout rises with age) and the pattern in differences (largest midterm drop-off among the young).",
  }),
  q({
    id: "us5-04",
    topicId: "usgov-political-parties",
    difficulty: "medium",
    concept: "Two-party system",
    stem: "Which of the following best explains the persistence of the two-party system in the United States?",
    choices: [
      ["The Constitution limits the number of parties that may appear on the ballot.", "The Constitution does not mention political parties."],
      ["Third parties are prohibited from receiving campaign contributions.", "Third parties can legally raise money."],
      ["Single-member districts with winner-take-all rules make it difficult for third parties to win seats.", "Correct. Finishing second earns nothing, so voters and donors gravitate to the two major parties."],
      ["Federal law requires voters to register with one of the two major parties.", "No federal law requires registration with a major party."],
    ],
    answer: "C",
    explanation: "Winner-take-all, single-member district elections create strong incentives for two dominant parties.",
  }),
  q({
    id: "us5-05",
    topicId: "usgov-political-parties",
    difficulty: "medium",
    concept: "Realignment",
    stem: "The 1932 presidential election is often described as a critical election because it",
    choices: [
      ["marked a durable shift in party coalitions that shaped politics for decades", "Correct. It helped build the New Deal coalition."],
      ["was the first election decided by the House of Representatives", "The House decided the elections of 1800 and 1824, not 1932."],
      ["was the first election in which women could vote", "Women gained the right to vote nationally in 1920."],
      ["ended the two-party system", "The two-party system continued."],
    ],
    answer: "A",
    explanation: "Critical elections signal realignments — lasting changes in which groups support which party.",
  }),
  q({
    id: "us5-06",
    topicId: "usgov-political-parties",
    difficulty: "hard",
    concept: "Third-party influence",
    stem: "Which of the following is the most common way third parties influence American politics?",
    choices: [
      ["Winning a majority of seats in state legislatures", "Third parties rarely win many legislative seats."],
      ["Controlling the Electoral College in close elections", "Third parties seldom win electoral votes."],
      ["Nominating Supreme Court justices", "Presidents nominate justices."],
      ["Raising issues that major parties later adopt", "Correct. Third parties can shape the agenda even when they lose."],
    ],
    answer: "D",
    explanation: "Major parties often absorb popular third-party issues, reducing the third party's appeal while changing policy debates.",
  }),
  q({
    id: "us5-07",
    topicId: "usgov-interest-groups",
    difficulty: "medium",
    concept: "Free-rider problem",
    stem: "Many consumers benefit from an advocacy group's successful campaign for stronger product safety rules, even though they never joined or donated to the group. This illustrates",
    choices: [
      ["the free-rider problem", "Correct. People benefit from collective goods without contributing, making large groups harder to organize."],
      ["an iron triangle", "An iron triangle links committees, agencies, and groups."],
      ["pluralism", "Pluralism is a model of group competition, not a problem of collective action."],
      ["a revolving door", "The revolving door describes officials moving into lobbying jobs."],
    ],
    answer: "A",
    explanation: "Groups offer selective benefits available only to members to overcome free riding.",
  }),
  q({
    id: "us5-08",
    topicId: "usgov-interest-groups",
    difficulty: "medium",
    concept: "Amicus curiae briefs",
    stem: "An interest group that is not a party to a Supreme Court case submits a brief arguing for a particular outcome. This is known as",
    choices: [
      ["a writ of certiorari", "A writ of certiorari is the Court's order to review a case."],
      ["an amicus curiae brief", "Correct. \"Friend of the court\" briefs let outside groups influence judicial decisions."],
      ["a discharge petition", "A discharge petition forces a bill out of a House committee."],
      ["a signing statement", "Signing statements are issued by presidents."],
    ],
    answer: "B",
    explanation: "Amicus briefs are a major way interest groups try to shape court decisions.",
  }),
  q({
    id: "us5-09",
    topicId: "usgov-interest-groups",
    difficulty: "hard",
    concept: "Access points",
    stem: "An interest group opposes a proposed federal regulation that has not yet been finalized. Which strategy targets the bureaucracy most directly?",
    choices: [
      ["Filing an amicus brief in a related Supreme Court case", "This targets the judiciary."],
      ["Endorsing candidates in upcoming congressional elections", "This targets elections and Congress."],
      ["Submitting formal comments during the agency's notice-and-comment period", "Correct. Public comment is the formal way to influence a proposed rule."],
      ["Organizing a march in the state capital", "This targets public opinion and state officials, not the federal agency."],
    ],
    answer: "C",
    explanation: "Agencies must consider public comments before issuing final rules, making rulemaking a key access point for groups.",
  }),
  q({
    id: "us5-10",
    topicId: "usgov-elections",
    difficulty: "medium",
    concept: "Electoral College strategy",
    stem: "Presidential candidates spend most of their time and money in a small number of states. Which feature of the Electoral College best explains this strategy?",
    choices: [
      ["Most states award all of their electoral votes to the candidate who wins the state's popular vote.", "Correct. Winner-take-all makes closely divided swing states most valuable."],
      ["Electors must vote for the candidate with the most money raised in their state.", "No such requirement exists."],
      ["The House chooses the president in every close election.", "The House chooses only if no candidate has an Electoral College majority."],
      ["Each state has the same number of electoral votes.", "States' electoral votes vary with House representation."],
    ],
    answer: "A",
    explanation: "Winner-take-all allocation means extra votes in safe states add nothing, so campaigns concentrate on competitive states.",
  }),
  q({
    id: "us5-11",
    topicId: "usgov-elections",
    difficulty: "medium",
    concept: "Incumbency advantage",
    stem: "Which of the following best explains why House incumbents win reelection at high rates?",
    choices: [
      ["Incumbents are exempt from primary elections.", "Incumbents can and sometimes do face primary challenges."],
      ["Incumbents benefit from name recognition, fundraising advantages, and casework for constituents.", "Correct. These advantages make incumbents difficult to defeat."],
      ["The Constitution guarantees incumbents two terms.", "No such guarantee exists."],
      ["Challengers are prohibited from running television ads.", "Challengers may advertise."],
    ],
    answer: "B",
    explanation: "Name recognition, franking, casework, fundraising networks, and favorable districts all contribute to incumbency advantage.",
  }),
  q({
    id: "us5-12",
    topicId: "usgov-elections",
    difficulty: "easy",
    concept: "Closed primaries",
    stem: "In a closed primary,",
    choices: [
      ["any registered voter may choose which party's primary to vote in", "That describes an open primary."],
      ["all candidates appear on a single ballot regardless of party", "That describes a top-two or blanket primary."],
      ["only voters registered with a party may vote in that party's primary", "Correct. Participation is limited to party members."],
      ["party members meet in person to discuss and select delegates", "That describes a caucus."],
    ],
    answer: "C",
    explanation: "Closed primaries limit participation to registered party members, which tends to favor candidates appealing to the party base.",
  }),
  q({
    id: "us5-13",
    topicId: "usgov-campaign-finance",
    difficulty: "medium",
    concept: "Citizens United v. FEC",
    stem: "In Citizens United v. FEC (2010), the Supreme Court held that",
    choices: [
      ["corporations may give unlimited contributions directly to candidates", "Direct contributions to candidates remain limited."],
      ["Congress may ban all political advertising within 60 days of an election", "The Court struck down restrictions on independent expenditures."],
      ["campaign spending is not protected by the First Amendment", "The Court treated political spending as protected speech."],
      ["the government may not prohibit independent political expenditures by corporations and unions", "Correct. The Court ruled such bans violate the First Amendment."],
    ],
    answer: "D",
    explanation: "Citizens United treated independent political spending as protected speech, contributing to the rise of super PACs.",
    caseIds: ["citizens-united-v-fec"],
  }),
  q({
    id: "us5-14",
    topicId: "usgov-campaign-finance",
    difficulty: "medium",
    concept: "Super PACs",
    stem: "Which statement accurately describes super PACs?",
    choices: [
      ["They may raise and spend unlimited amounts but cannot coordinate with candidates' campaigns.", "Correct. Independence from campaigns is the legal basis for unlimited super PAC spending."],
      ["They may give unlimited contributions directly to candidates.", "Super PACs can't contribute directly to candidates."],
      ["They are prohibited from running advertisements about candidates.", "Super PACs frequently run ads supporting or opposing candidates."],
      ["They are regulated exclusively by state governments.", "Federal super PACs are regulated under federal law and file with the FEC."],
    ],
    answer: "A",
    explanation: "Super PACs are independent-expenditure-only committees; coordination with a candidate would make their spending a contribution subject to limits.",
  }),
  q({
    id: "us5-15",
    topicId: "usgov-campaign-finance",
    difficulty: "hard",
    concept: "Contribution vs. expenditure",
    stem: "Following Citizens United v. FEC (2010), which of the following remains subject to federal limits?",
    choices: [
      ["Independent expenditures by corporations", "Citizens United removed limits on these."],
      ["Spending by super PACs", "Super PACs may spend unlimited amounts independently."],
      ["Contributions from individuals directly to a candidate's campaign", "Correct. Direct contributions to candidates are still capped."],
      ["Independent expenditures by labor unions", "Citizens United applied to unions as well as corporations."],
    ],
    answer: "C",
    explanation: "The key legal line runs between contributions (limited) and independent expenditures (unlimited). Coordination is what turns spending into a contribution.",
    caseIds: ["citizens-united-v-fec", "buckley-v-valeo"],
  }),
  q({
    id: "us5-16",
    topicId: "usgov-media",
    difficulty: "easy",
    concept: "Horse-race journalism",
    stem: "News coverage that focuses on which candidate is ahead in the polls rather than on candidates' policy positions is called",
    choices: [
      ["watchdog journalism", "Watchdog journalism investigates wrongdoing."],
      ["horse-race journalism", "Correct. Horse-race coverage emphasizes who's winning or losing."],
      ["agenda setting", "Agenda setting concerns which issues receive attention."],
      ["gatekeeping", "Gatekeeping is deciding what news to cover."],
    ],
    answer: "B",
    explanation: "Horse-race coverage reflects the media's scorekeeper role and is often criticized for crowding out policy substance.",
  }),
  q({
    id: "us5-17",
    topicId: "usgov-media",
    difficulty: "medium",
    concept: "Watchdog role",
    stem: "A newspaper investigation reveals that a federal agency misused funds, prompting congressional hearings. This illustrates the media's role as",
    choices: [
      ["scorekeeper", "Scorekeeping tracks political wins and losses."],
      ["gatekeeper", "Gatekeeping decides which issues receive attention; investigation of misconduct is the watchdog role."],
      ["watchdog", "Correct. Investigative reporting holds officials accountable."],
      ["pollster", "The scenario involves investigation, not polling."],
    ],
    answer: "C",
    explanation: "As watchdog, the media scrutinizes officials' conduct, sometimes triggering oversight by other institutions.",
  }),
  q({
    id: "us5-18",
    topicId: "usgov-media",
    difficulty: "hard",
    concept: "Media and polarization",
    stem: "Which of the following best explains how changes in the media environment may contribute to political polarization?",
    choices: [
      ["Traditional networks have become more influential, creating a shared national narrative.", "A shared narrative would likely reduce, not increase, polarization."],
      ["The FCC now requires all news outlets to present both sides of every issue.", "No such requirement currently exists for news outlets."],
      ["Social media prevents users from seeing political content.", "Social media exposes users to substantial political content."],
      ["People can choose partisan outlets and algorithm-driven feeds that reinforce existing views.", "Correct. Selective exposure and echo chambers can deepen partisan divisions."],
    ],
    answer: "D",
    explanation: "A fragmented media landscape lets people consume information consistent with their existing beliefs, reinforcing partisan differences.",
  }),
];
