import { bank } from "./helpers";

const q = bank("usgov", "usgov-u2");

export const usgovU2Questions = [
  q({
    id: "us2-01",
    topicId: "usgov-congress-structure",
    difficulty: "easy",
    concept: "Unique House powers",
    stem: "Which of the following is a power held only by the House of Representatives?",
    choices: [
      ["Confirming federal judges", "Confirmation is a Senate power."],
      ["Ratifying treaties", "Treaty ratification requires two-thirds of the Senate."],
      ["Initiating revenue bills", "Correct. Article I requires bills for raising revenue to originate in the House."],
      ["Trying impeachments", "The Senate tries impeachments; the House brings the charges."],
    ],
    answer: "C",
    explanation: "Unique House powers include originating revenue bills and impeachment. The Senate confirms appointments, ratifies treaties, and tries impeachments.",
  }),
  q({
    id: "us2-02",
    topicId: "usgov-congress-structure",
    difficulty: "medium",
    concept: "Models of representation",
    stem: "A representative votes against a bill that most of her constituents support because she believes it would harm the nation's long-term economic health. She is acting most consistently with which model of representation?",
    choices: [
      ["Trustee", "Correct. A trustee uses independent judgment about the public good, even against constituent preferences."],
      ["Delegate", "A delegate would follow constituents' preferences."],
      ["Politico", "A politico shifts between roles; the scenario describes a clear exercise of independent judgment."],
      ["Partisan", "Nothing in the scenario indicates she is following her party's position."],
    ],
    answer: "A",
    explanation: "The trustee model holds that representatives should use their own judgment. Delegates mirror constituents; politicos blend both depending on the issue.",
  }),
  q({
    id: "us2-03",
    topicId: "usgov-congress-structure",
    difficulty: "hard",
    concept: "Senate design",
    stem: "Which feature of the Senate best explains why the Framers expected it to be more deliberative and less responsive to short-term public opinion than the House?",
    choices: [
      ["Senators represent smaller, more homogeneous districts.", "Senators represent entire states, which are larger and usually more diverse than House districts."],
      ["Senators serve six-year staggered terms.", "Correct. Longer, staggered terms insulate senators from sudden shifts in public opinion."],
      ["The Senate has a Rules Committee that strictly limits debate.", "Strict debate limits are a House feature; the Senate allows extended debate."],
      ["Senators have always been appointed by governors.", "Senators were chosen by state legislatures until 1913 and are now directly elected."],
    ],
    answer: "B",
    explanation: "Six-year terms, with only a third of seats up at once, give the Senate stability and distance from short-term swings in opinion.",
  }),
  q({
    id: "us2-04",
    topicId: "usgov-lawmaking",
    difficulty: "medium",
    concept: "Filibuster and cloture",
    stem: "A bill is supported by 55 senators but never receives a final vote in the Senate. Which is the most likely explanation?",
    choices: [
      ["The House Rules Committee refused to schedule the bill.", "The House Rules Committee controls House, not Senate, procedure."],
      ["The president issued a pocket veto before the Senate voted.", "A pocket veto applies only to bills that have passed both chambers."],
      ["Passage in the Senate requires a two-thirds vote.", "Ordinary legislation passes the Senate by a simple majority."],
      ["Supporters could not reach the 60 votes needed for cloture to end a filibuster.", "Correct. Without cloture, a filibuster can prevent a final vote."],
    ],
    answer: "D",
    explanation: "Cloture on most legislation requires three-fifths of senators (60). A minority can block bills that have majority support.",
  }),
  q({
    id: "us2-05",
    topicId: "usgov-lawmaking",
    difficulty: "medium",
    concept: "House Rules Committee",
    stem: "The House Rules Committee is significant primarily because it",
    choices: [
      ["sets the terms of debate and amendment for most bills, giving the majority party agenda control", "Correct. By setting rules for floor consideration, the committee helps the majority leadership shape outcomes."],
      ["confirms presidential nominees before they go to the Senate", "The House has no role in confirmations."],
      ["reconciles differences between House and Senate versions of a bill", "That is the function of a conference committee."],
      ["writes the annual federal budget", "Budgets involve the president's proposal and the budget and appropriations committees."],
    ],
    answer: "A",
    explanation: "Closed or structured rules limit amendments and debate, making the Rules Committee a key tool of the Speaker and majority party.",
  }),
  q({
    id: "us2-06",
    topicId: "usgov-lawmaking",
    difficulty: "hard",
    concept: "Mandatory spending",
    stem: "Which of the following best explains why Congress has limited ability to reduce federal spending through the annual appropriations process?",
    choices: [
      ["The president sets the final budget, and Congress may only approve it.", "Congress holds the power of the purse; the president proposes a budget."],
      ["Mandatory spending, such as Social Security and Medicare, is set by existing law rather than annual appropriations.", "Correct. Entitlements make up the largest share of spending and continue unless Congress changes the underlying laws."],
      ["The Supreme Court must approve any reduction in spending.", "Courts don't approve budgets."],
      ["The Constitution prohibits reducing spending below the prior year's level.", "No such constitutional provision exists."],
    ],
    answer: "B",
    explanation: "Because most federal spending is mandatory, only discretionary spending is decided each year, which constrains budget cuts.",
  }),
  q({
    id: "us2-07",
    topicId: "usgov-lawmaking",
    difficulty: "hard",
    concept: "Gerrymandering and polarization",
    stem: "Which is the most likely consequence of widespread partisan gerrymandering of House districts?",
    choices: [
      ["More competitive general elections", "Gerrymandering typically reduces general-election competition."],
      ["Increased representation of third parties", "District manipulation benefits major parties, not third parties."],
      ["More safe seats whose members focus on primary voters, contributing to polarization", "Correct. When the general election is safe, the primary is the real contest, pulling members toward their party's base."],
      ["Reduced advantages for incumbents", "Safe districts generally strengthen incumbents."],
    ],
    answer: "C",
    explanation: "Safe seats shift the key electoral threat to primaries, where more ideological voters participate — a common explanation for congressional polarization.",
  }),
  q({
    id: "us2-08",
    topicId: "usgov-presidential-powers",
    difficulty: "medium",
    concept: "Federalist No. 70",
    stimulus: {
      kind: "text",
      text: "\"Energy in the Executive is a leading character in the definition of good government.... Decision, activity, secrecy, and despatch will generally characterise the proceedings of one man in a much more eminent degree than the proceedings of any greater number.\"",
      source: "Alexander Hamilton, Federalist No. 70, 1788",
    },
    stem: "Which of the following best summarizes Hamilton's argument?",
    choices: [
      ["An executive council would better protect liberty than a single president.", "Hamilton argues the opposite, rejecting a plural executive."],
      ["Congress should select the president to ensure accountability.", "The excerpt concerns the structure of the executive, not how it is chosen."],
      ["The president should serve a single term to avoid concentrating power.", "Hamilton supported eligibility for reelection."],
      ["A single executive can act decisively, which is essential to good government.", "Correct. Hamilton argues unity produces energy — speed, decisiveness, and accountability."],
    ],
    answer: "D",
    explanation: "Federalist No. 70 defends a unitary executive: one person can act with speed and secrecy, and voters know whom to hold responsible.",
    documentIds: ["federalist-70"],
  }),
  q({
    id: "us2-09",
    topicId: "usgov-presidential-powers",
    difficulty: "easy",
    concept: "Executive agreements",
    stem: "A president signs an agreement with a foreign government on trade enforcement without submitting it to the Senate. This is an example of",
    choices: [
      ["an executive agreement", "Correct. Executive agreements are international agreements that don't require Senate ratification."],
      ["a treaty", "Treaties require approval by two-thirds of the Senate."],
      ["a signing statement", "Signing statements accompany bills the president signs into law."],
      ["a pocket veto", "A pocket veto concerns bills from Congress, not foreign agreements."],
    ],
    answer: "A",
    explanation: "Presidents use executive agreements to avoid the two-thirds Senate threshold, though these agreements can be reversed more easily than treaties.",
  }),
  q({
    id: "us2-10",
    topicId: "usgov-presidential-powers",
    difficulty: "medium",
    concept: "Executive orders",
    stem: "Which of the following describes a significant limitation of executive orders as a policymaking tool?",
    choices: [
      ["They must be ratified by two-thirds of the Senate.", "Executive orders don't require Senate approval."],
      ["They can be revoked by a later president and struck down by courts.", "Correct. Executive orders lack the durability of statutes and must rest on legal authority."],
      ["They apply only during declared wars.", "Executive orders are used in all policy areas."],
      ["They must be approved by the House before taking effect.", "No congressional approval is required."],
    ],
    answer: "B",
    explanation: "Because executive orders are unilateral, the next president can reverse them, Congress can supersede them by law, and courts can invalidate them.",
  }),
  q({
    id: "us2-11",
    topicId: "usgov-presidential-checks",
    difficulty: "medium",
    concept: "Going public",
    stem: "A president facing opposition in Congress travels to several states to give speeches urging voters to contact their senators about a proposed bill. This strategy is best described as",
    choices: [
      ["logrolling", "Logrolling is vote-trading among legislators."],
      ["executive privilege", "Executive privilege is the claimed right to withhold information."],
      ["going public", "Correct. Presidents appeal directly to the public to pressure Congress."],
      ["a signing statement", "Signing statements accompany bills being signed into law."],
    ],
    answer: "C",
    explanation: "Going public uses the bully pulpit to build public pressure on legislators whose constituents support the president's position.",
  }),
  q({
    id: "us2-12",
    topicId: "usgov-presidential-checks",
    difficulty: "medium",
    concept: "War Powers Resolution",
    stem: "The War Powers Resolution (1973) attempted to limit presidential power by",
    choices: [
      ["prohibiting the president from deploying troops without a declaration of war", "It allows deployments but imposes notification and time limits."],
      ["requiring Senate confirmation of military commanders in the field", "Commanders are not confirmed on a per-deployment basis under the resolution."],
      ["giving the Supreme Court authority to approve military actions", "The resolution does not involve the courts."],
      ["requiring the president to notify Congress within 48 hours and limiting deployments without authorization", "Correct. Forces must be withdrawn after 60 days (plus 30 for withdrawal) unless Congress authorizes the action."],
    ],
    answer: "D",
    explanation: "Passed over President Nixon's veto, the resolution sought to restore Congress's role in decisions to use force. Presidents have often questioned its constitutionality.",
  }),
  q({
    id: "us2-13",
    topicId: "usgov-presidential-checks",
    difficulty: "hard",
    concept: "Judicial appointments",
    stem: "Senate confirmation battles over Supreme Court nominees have become especially intense primarily because",
    choices: [
      ["justices serve during good behavior and can shape policy for decades", "Correct. Life tenure means one appointment can influence constitutional interpretation long after a president leaves office."],
      ["the president can remove justices who disagree with administration policy", "Justices can only be removed through impeachment and conviction."],
      ["the Senate elects justices from a list provided by the president", "The president nominates; the Senate confirms or rejects."],
      ["justices must belong to the president's political party", "No party requirement exists."],
    ],
    answer: "A",
    explanation: "Because justices serve for life and vacancies are unpredictable, each confirmation carries long-term policy stakes, increasing partisan conflict.",
  }),
  q({
    id: "us2-14",
    topicId: "usgov-judiciary",
    difficulty: "easy",
    concept: "Marbury v. Madison",
    stem: "The significance of Marbury v. Madison (1803) is that it",
    choices: [
      ["established the Supreme Court's power of judicial review", "Correct. The Court held that part of the Judiciary Act of 1789 was unconstitutional, asserting the power to review acts of Congress."],
      ["upheld Congress's power to create a national bank", "That was McCulloch v. Maryland (1819)."],
      ["applied the Bill of Rights to the states", "Incorporation came through later cases under the Fourteenth Amendment."],
      ["expanded the Court's original jurisdiction", "The Court refused to accept an expansion of its original jurisdiction."],
    ],
    answer: "A",
    explanation: "By striking down a statute that conflicted with Article III, the Court claimed the power to declare laws unconstitutional.",
    caseIds: ["marbury-v-madison"],
  }),
  q({
    id: "us2-15",
    topicId: "usgov-judiciary",
    difficulty: "medium",
    concept: "Federalist No. 78",
    stimulus: {
      kind: "text",
      text: "\"The judiciary... has no influence over either the sword or the purse.... It may truly be said to have neither FORCE nor WILL, but merely judgment.\"",
      source: "Alexander Hamilton, Federalist No. 78, 1788",
    },
    stem: "Which of the following best explains Hamilton's reasoning in the excerpt?",
    choices: [
      ["Judges should be elected so they remain accountable to voters.", "Hamilton defended tenure during good behavior, not elections."],
      ["Because courts depend on other branches to enforce rulings, the judiciary is the least dangerous branch.", "Correct. Without control of the military or funding, courts pose little threat to liberty."],
      ["The judiciary should be subordinate to Congress in interpreting the Constitution.", "Hamilton argued courts should interpret the Constitution and void conflicting laws."],
      ["Courts should avoid ruling on the constitutionality of laws.", "Hamilton supported what became judicial review."],
    ],
    answer: "B",
    explanation: "Federalist No. 78 argues the judiciary is weak by design, so life tenure is needed to preserve its independence.",
    documentIds: ["federalist-78"],
  }),
  q({
    id: "us2-16",
    topicId: "usgov-judiciary",
    difficulty: "hard",
    concept: "Checks on the judiciary",
    stem: "The Supreme Court interprets a federal statute in a way that most members of Congress believe is contrary to the law's purpose. Which is the most direct way for Congress to respond?",
    choices: [
      ["Overrule the decision by simple resolution", "Congress cannot overrule a court decision by resolution."],
      ["Remove the justices in the majority by a majority vote", "Justices can be removed only through impeachment and conviction for misconduct."],
      ["Pass new legislation clarifying the statute's meaning", "Correct. When the Court interprets a statute (rather than the Constitution), Congress can respond by amending the law."],
      ["Ask the president to veto the Court's decision", "The president has no power to veto court decisions."],
    ],
    answer: "C",
    explanation: "Statutory interpretation can be addressed by new legislation. Constitutional rulings can only be changed by amendment or by the Court itself.",
  }),
  q({
    id: "us2-17",
    topicId: "usgov-bureaucracy",
    difficulty: "medium",
    concept: "Iron triangle",
    stem: "An iron triangle consists of which three actors?",
    choices: [
      ["The president, the Speaker of the House, and the Senate majority leader", "These are leaders of branches and chambers, not an iron triangle."],
      ["A political party, a super PAC, and a media outlet", "These are campaign actors, not policy subsystems."],
      ["The Supreme Court, the solicitor general, and an interest group", "This does not describe the stable policymaking relationship of an iron triangle."],
      ["A congressional committee, a bureaucratic agency, and an interest group", "Correct. These three mutually benefit from a stable policy relationship."],
    ],
    answer: "D",
    explanation: "Committees fund and oversee agencies, agencies implement programs benefiting interest groups, and groups support committee members — a self-reinforcing triangle.",
  }),
  q({
    id: "us2-18",
    topicId: "usgov-bureaucracy",
    difficulty: "medium",
    concept: "Bureaucratic discretion",
    stem: "Which of the following is the best example of bureaucratic discretion?",
    choices: [
      ["The Environmental Protection Agency sets a specific emissions limit to implement a law requiring \"safe\" air quality.", "Correct. The agency decides how to carry out a broadly written statute."],
      ["Congress passes a law creating a new cabinet department.", "This is a legislative action."],
      ["The president nominates a new secretary of transportation.", "This is an appointment, not an agency exercising discretion."],
      ["The Supreme Court strikes down a federal regulation.", "This is judicial review of agency action."],
    ],
    answer: "A",
    explanation: "When statutes are broad, agencies use discretion to write specific rules — a key way unelected bureaucrats shape policy.",
  }),
  q({
    id: "us2-19",
    topicId: "usgov-bureaucracy",
    difficulty: "easy",
    concept: "Pendleton Act",
    stem: "The Pendleton Civil Service Act of 1883 was significant because it",
    choices: [
      ["created the first cabinet departments", "Cabinet departments date to the 1789 Washington administration."],
      ["began replacing the patronage (spoils) system with merit-based hiring", "Correct. The act created a merit-based civil service."],
      ["gave the president power to fire all federal employees", "The act protected many employees from political firing."],
      ["established independent regulatory commissions", "Independent commissions developed separately, beginning with the Interstate Commerce Commission in 1887."],
    ],
    answer: "B",
    explanation: "After President Garfield's assassination by a disappointed office seeker, Congress moved toward a professional, merit-based civil service.",
  }),
  q({
    id: "us2-20",
    topicId: "usgov-bureaucratic-accountability",
    difficulty: "easy",
    concept: "Congressional oversight",
    stem: "Which of the following is an example of congressional oversight of the bureaucracy?",
    choices: [
      ["A federal judge rules that an agency exceeded its statutory authority.", "This is judicial review, not congressional oversight."],
      ["The president issues an executive order directing agency priorities.", "This is presidential control, not congressional oversight."],
      ["A House committee holds hearings on an agency's handling of disaster relief.", "Correct. Hearings are a primary tool of congressional oversight."],
      ["An interest group submits comments on a proposed regulation.", "This is interest group participation in rulemaking."],
    ],
    answer: "C",
    explanation: "Oversight includes hearings, investigations, and reporting requirements that let Congress monitor how laws are implemented.",
  }),
  q({
    id: "us2-21",
    topicId: "usgov-bureaucratic-accountability",
    difficulty: "hard",
    concept: "Limiting agency discretion",
    stem: "Congress believes an independent regulatory commission has interpreted its authority too broadly. Which action would most directly limit the commission's discretion?",
    choices: [
      ["Asking governors to veto the commission's regulations", "Governors have no authority over federal regulations."],
      ["Requesting an advisory opinion from the Supreme Court", "Federal courts don't issue advisory opinions."],
      ["Relying on the president to remove commissioners at will", "Independent commissioners often have protection from removal without cause, and this relies on the executive, not Congress."],
      ["Amending the statute to narrow the commission's authority", "Correct. Congress can rewrite the law that delegates authority to the agency."],
    ],
    answer: "D",
    explanation: "Because agencies act under delegated authority, Congress can narrow, expand, or clarify that authority by statute — the most direct congressional check.",
  }),
  q({
    id: "us2-22",
    topicId: "usgov-bureaucratic-accountability",
    difficulty: "medium",
    concept: "Presidential control of the bureaucracy",
    stem: "A newly elected president wants a cabinet department to change how it enforces an existing law. Which action would most directly accomplish this without new legislation?",
    choices: [
      ["Asking the Supreme Court to reinterpret the law", "Courts decide cases brought before them; they don't reinterpret laws at a president's request."],
      ["Appointing a new department secretary and issuing an executive order setting enforcement priorities", "Correct. Appointments and executive orders are the president's main tools for directing how agencies implement laws."],
      ["Reducing the department's budget without congressional approval", "Congress controls appropriations; the president can't cut funding unilaterally."],
      ["Holding oversight hearings on the department's performance", "Oversight hearings are a congressional tool."],
    ],
    answer: "B",
    explanation: "Presidents shape bureaucratic behavior through appointments, executive orders, and management priorities — within the limits of the statutes Congress has written.",
  }),
];
