import { bank } from "./helpers";

const q = bank("usgov", "usgov-u3");

export const usgovU3Questions = [
  q({
    id: "us3-01",
    topicId: "usgov-bill-of-rights-incorporation",
    difficulty: "medium",
    concept: "Selective incorporation",
    stem: "The Supreme Court has applied most protections of the Bill of Rights to the states primarily through which constitutional provision?",
    choices: [
      ["The Tenth Amendment", "The Tenth Amendment reserves powers to states; it doesn't apply rights against them."],
      ["The Due Process Clause of the Fourteenth Amendment", "Correct. The Court held that the \"liberty\" protected by due process includes most Bill of Rights guarantees."],
      ["The Supremacy Clause", "The Supremacy Clause establishes national law's supremacy but is not the basis for incorporation."],
      ["The Equal Protection Clause of the Fourteenth Amendment", "Equal protection addresses discrimination, not incorporation."],
    ],
    answer: "B",
    explanation: "Selective incorporation uses the Fourteenth Amendment's Due Process Clause to apply Bill of Rights protections to the states, case by case.",
  }),
  q({
    id: "us3-02",
    topicId: "usgov-bill-of-rights-incorporation",
    difficulty: "medium",
    concept: "McDonald v. Chicago",
    stem: "In McDonald v. Chicago (2010), the Supreme Court held that",
    choices: [
      ["Congress may not regulate firearms under the Commerce Clause", "That reasoning is associated with United States v. Lopez."],
      ["the Second Amendment protects only the right of state militias to bear arms", "The Court had already recognized an individual right in District of Columbia v. Heller (2008)."],
      ["the Second Amendment right to keep and bear arms applies to state and local governments", "Correct. The Court incorporated the Second Amendment through the Due Process Clause."],
      ["states must provide attorneys to defendants who cannot afford them", "That was Gideon v. Wainwright (1963)."],
    ],
    answer: "C",
    explanation: "McDonald struck down Chicago's handgun ban by holding that the Second Amendment is incorporated against states — a key example of selective incorporation.",
    caseIds: ["mcdonald-v-chicago"],
  }),
  q({
    id: "us3-03",
    topicId: "usgov-bill-of-rights-incorporation",
    difficulty: "hard",
    concept: "Civil liberties vs. civil rights",
    stem: "Which of the following scenarios is best categorized as a civil rights issue rather than a civil liberties issue?",
    choices: [
      ["A state law bans the burning of the American flag as a form of protest.", "This concerns freedom of expression — a civil liberty."],
      ["Police search a car without a warrant or probable cause.", "This concerns Fourth Amendment protections — a civil liberty."],
      ["A public school leads students in a daily prayer.", "This concerns the Establishment Clause — a civil liberty."],
      ["A hotel refuses to rent rooms to guests because of their race.", "Correct. Unequal treatment based on group membership is a civil rights issue."],
    ],
    answer: "D",
    explanation: "Civil liberties limit government interference with freedoms; civil rights protect against discrimination and guarantee equal treatment.",
  }),
  q({
    id: "us3-04",
    topicId: "usgov-freedom-of-religion",
    difficulty: "easy",
    concept: "Engel v. Vitale",
    stem: "In Engel v. Vitale (1962), the Supreme Court ruled that",
    choices: [
      ["school-sponsored prayer in public schools violates the Establishment Clause", "Correct. Even a voluntary, nondenominational prayer written by state officials was unconstitutional."],
      ["Amish parents could not be required to send children to high school", "That was Wisconsin v. Yoder (1972)."],
      ["students could wear armbands to protest the Vietnam War", "That was Tinker v. Des Moines (1969)."],
      ["public schools may not teach about religion in any form", "Teaching about religion is permitted; the issue was government-sponsored prayer."],
    ],
    answer: "A",
    explanation: "Engel established that government may not compose or sponsor official prayers in public schools.",
    caseIds: ["engel-v-vitale"],
  }),
  q({
    id: "us3-05",
    topicId: "usgov-freedom-of-religion",
    difficulty: "medium",
    concept: "Wisconsin v. Yoder",
    stem: "Wisconsin v. Yoder (1972) is most directly an example of the Court protecting",
    choices: [
      ["freedom of speech in public schools", "Yoder concerned religious practice, not speech."],
      ["the free exercise of religion against a generally applicable state law", "Correct. The Court exempted Amish families from compulsory schooling beyond eighth grade."],
      ["separation of church and state under the Establishment Clause", "Yoder is a Free Exercise case."],
      ["the right to privacy under the Due Process Clause", "The ruling rested on free exercise, not privacy."],
    ],
    answer: "B",
    explanation: "The Court held that Wisconsin's interest in two more years of schooling did not outweigh the Amish families' religious freedom.",
    caseIds: ["wisconsin-v-yoder"],
  }),
  q({
    id: "us3-06",
    topicId: "usgov-freedom-of-religion",
    difficulty: "hard",
    concept: "Establishment Clause application",
    stem: "A state legislature passes a law requiring every public school teacher to begin the day by leading students in a short prayer composed by the state education department. Which required case would provide the strongest precedent for challenging the law?",
    choices: [
      ["Wisconsin v. Yoder", "Yoder protected free exercise; this law raises establishment concerns."],
      ["Tinker v. Des Moines", "Tinker concerned student symbolic speech."],
      ["Engel v. Vitale", "Correct. Engel struck down a state-written prayer in public schools as a violation of the Establishment Clause."],
      ["United States v. Lopez", "Lopez concerned the limits of the Commerce Clause."],
    ],
    answer: "C",
    explanation: "The facts closely parallel Engel: government-composed prayer led in public schools.",
    caseIds: ["engel-v-vitale"],
  }),
  q({
    id: "us3-07",
    topicId: "usgov-speech-press",
    difficulty: "medium",
    concept: "Tinker v. Des Moines",
    stem: "According to the Supreme Court's decision in Tinker v. Des Moines (1969), public school officials may restrict student speech when",
    choices: [
      ["the speech expresses a political viewpoint", "Tinker protected political speech; viewpoint alone isn't a basis for restriction."],
      ["the speech would cause a substantial disruption of the educational process", "Correct. Absent substantial disruption, symbolic student speech is protected."],
      ["any student or parent objects to the speech", "Mere discomfort or objection is not sufficient under Tinker."],
      ["the speech occurs during school hours", "Students don't lose rights \"at the schoolhouse gate.\""],
    ],
    answer: "B",
    explanation: "Tinker set the substantial disruption standard for student speech. Later cases like Morse v. Frederick recognized additional limits.",
    caseIds: ["tinker-v-des-moines"],
  }),
  q({
    id: "us3-08",
    topicId: "usgov-speech-press",
    difficulty: "medium",
    concept: "Schenck v. United States",
    stem: "In Schenck v. United States (1919), the Supreme Court upheld the conviction of a man who distributed leaflets opposing the military draft. The Court reasoned that",
    choices: [
      ["speech creating a clear and present danger of harms Congress may prevent is not protected", "Correct. The Court emphasized wartime context and introduced the clear and present danger test."],
      ["political speech is never protected during wartime", "The Court did not hold that all wartime political speech is unprotected."],
      ["prior restraint of publications is presumed unconstitutional", "That principle is associated with New York Times Co. v. United States."],
      ["advocacy is protected unless it incites imminent lawless action", "That is the later Brandenburg v. Ohio (1969) standard."],
    ],
    answer: "A",
    explanation: "Schenck's clear and present danger test allowed restrictions on speech in wartime. Brandenburg later adopted a more protective standard.",
    caseIds: ["schenck-v-united-states"],
  }),
  q({
    id: "us3-09",
    topicId: "usgov-speech-press",
    difficulty: "hard",
    concept: "Prior restraint",
    stem: "A newspaper obtains classified documents about a past military operation and prepares to publish them. The federal government seeks a court order to block publication. Based on New York Times Co. v. United States (1971), the government would most likely",
    choices: [
      ["succeed, because national security claims always override the First Amendment", "The Court rejected blanket deference to national security claims."],
      ["succeed, because the documents are classified", "Classification alone did not justify prior restraint in the Pentagon Papers case."],
      ["fail, because the press is exempt from all criminal laws", "The case did not exempt the press from all laws; it addressed prior restraint."],
      ["fail, unless it can meet the heavy burden required to justify prior restraint", "Correct. Prior restraint carries a heavy presumption against its constitutionality."],
    ],
    answer: "D",
    explanation: "In the Pentagon Papers case, the Court ruled 6–3 that the government had not met its heavy burden to justify blocking publication.",
    caseIds: ["nyt-v-united-states"],
  }),
  q({
    id: "us3-10",
    topicId: "usgov-rights-of-accused",
    difficulty: "easy",
    concept: "Gideon v. Wainwright",
    stem: "In Gideon v. Wainwright (1963), the Supreme Court held that",
    choices: [
      ["police must inform suspects of their rights before interrogation", "That was Miranda v. Arizona (1966)."],
      ["evidence obtained through illegal searches may not be used in state courts", "That was Mapp v. Ohio (1961)."],
      ["states must provide attorneys to defendants in felony cases who cannot afford one", "Correct. The Sixth Amendment right to counsel was incorporated against the states."],
      ["the death penalty is always cruel and unusual punishment", "Gideon addressed counsel, not capital punishment."],
    ],
    answer: "C",
    explanation: "Gideon incorporated the Sixth Amendment right to counsel through the Fourteenth Amendment, leading to expanded public defender systems.",
    caseIds: ["gideon-v-wainwright"],
  }),
  q({
    id: "us3-11",
    topicId: "usgov-rights-of-accused",
    difficulty: "medium",
    concept: "Exclusionary rule",
    stem: "The exclusionary rule, which generally prevents illegally obtained evidence from being used at trial, is most closely associated with which amendment?",
    choices: [
      ["Fourth Amendment", "Correct. The rule enforces the protection against unreasonable searches and seizures."],
      ["Fifth Amendment", "The Fifth Amendment protects against self-incrimination and double jeopardy."],
      ["Sixth Amendment", "The Sixth Amendment covers counsel, jury, and speedy trial rights."],
      ["Eighth Amendment", "The Eighth Amendment covers bail, fines, and punishment."],
    ],
    answer: "A",
    explanation: "Mapp v. Ohio (1961) applied the exclusionary rule to the states to deter unconstitutional searches.",
    caseIds: ["mapp-v-ohio"],
  }),
  q({
    id: "us3-12",
    topicId: "usgov-rights-of-accused",
    difficulty: "medium",
    concept: "Miranda rights",
    stem: "Miranda warnings — including the right to remain silent — are designed primarily to protect which right?",
    choices: [
      ["The right to a speedy trial", "Speedy trial rights come from the Sixth Amendment and are unrelated to interrogation warnings."],
      ["The right against self-incrimination", "Correct. The warnings protect the Fifth Amendment privilege during custodial interrogation."],
      ["The right to an impartial jury", "Jury rights come from the Sixth Amendment."],
      ["The right against excessive bail", "Bail protections come from the Eighth Amendment."],
    ],
    answer: "B",
    explanation: "Miranda v. Arizona (1966) required police to inform suspects in custody of their rights to protect against compelled self-incrimination.",
    caseIds: ["miranda-v-arizona"],
  }),
  q({
    id: "us3-13",
    topicId: "usgov-privacy-due-process",
    difficulty: "medium",
    concept: "Griswold v. Connecticut",
    stem: "Griswold v. Connecticut (1965) is significant because the Court",
    choices: [
      ["held that the Second Amendment applies to the states", "That was McDonald v. Chicago (2010)."],
      ["upheld a state ban on contraceptives as a valid exercise of police power", "The Court struck down the ban."],
      ["recognized a constitutional right to privacy not explicitly stated in the text", "Correct. The Court found privacy implied by several amendments and due process."],
      ["ruled that abortion regulation belongs to the states", "That describes Dobbs (2022)."],
    ],
    answer: "C",
    explanation: "Griswold found a right to marital privacy in the \"penumbras\" of the Bill of Rights, laying the groundwork for later privacy cases.",
    caseIds: ["griswold-v-connecticut"],
  }),
  q({
    id: "us3-14",
    topicId: "usgov-privacy-due-process",
    difficulty: "medium",
    concept: "Dobbs v. Jackson",
    stem: "Which of the following best describes the effect of Dobbs v. Jackson Women's Health Organization (2022)?",
    choices: [
      ["It established a nationwide ban on abortion.", "Dobbs did not ban abortion; it removed federal constitutional protection."],
      ["It required states to protect abortion access in their constitutions.", "Dobbs placed no such requirement on states."],
      ["It incorporated the right to privacy against the states.", "Dobbs narrowed, rather than expanded, privacy-based protections."],
      ["It overturned Roe v. Wade and returned abortion regulation to elected officials.", "Correct. States now set abortion policy, producing wide variation."],
    ],
    answer: "D",
    explanation: "Dobbs held that the Constitution does not confer a right to abortion, overturning Roe and Casey and shifting policy to the states and Congress.",
    caseIds: ["dobbs-v-jackson"],
  }),
  q({
    id: "us3-15",
    topicId: "usgov-privacy-due-process",
    difficulty: "hard",
    concept: "Precedent and stare decisis",
    stem: "Both Brown v. Board of Education (1954) and Dobbs v. Jackson Women's Health Organization (2022) illustrate which feature of the Supreme Court?",
    choices: [
      ["The Court's willingness, at times, to overturn its own precedents", "Correct. Brown rejected Plessy's \"separate but equal\"; Dobbs overturned Roe."],
      ["The Court's reliance on the Commerce Clause to expand federal power", "Neither case was decided under the Commerce Clause."],
      ["The Court's refusal to hear cases involving the states", "Both cases involved state laws."],
      ["The Court's consistent use of judicial restraint", "Overturning precedent is often described as activism, not restraint."],
    ],
    answer: "A",
    explanation: "Although stare decisis promotes stability, the Court can depart from precedent. Brown and Dobbs are prominent examples from very different eras.",
    caseIds: ["brown-v-board", "dobbs-v-jackson"],
  }),
  q({
    id: "us3-16",
    topicId: "usgov-civil-rights",
    difficulty: "easy",
    concept: "Brown v. Board of Education",
    stem: "In Brown v. Board of Education (1954), the Supreme Court held that racial segregation in public schools violated",
    choices: [
      ["the Establishment Clause of the First Amendment", "The case concerned racial equality, not religion."],
      ["the Due Process Clause of the Fifth Amendment", "Brown rested on the Fourteenth Amendment's Equal Protection Clause."],
      ["the Equal Protection Clause of the Fourteenth Amendment", "Correct. The Court held that separate educational facilities are inherently unequal."],
      ["the Commerce Clause", "The Commerce Clause was used later to uphold the Civil Rights Act of 1964, not in Brown."],
    ],
    answer: "C",
    explanation: "Brown overturned Plessy v. Ferguson's \"separate but equal\" doctrine in public education.",
    caseIds: ["brown-v-board", "plessy-v-ferguson"],
  }),
  q({
    id: "us3-17",
    topicId: "usgov-civil-rights",
    difficulty: "medium",
    concept: "Letter from Birmingham Jail",
    stem: "In the Letter from Birmingham Jail, Martin Luther King Jr. primarily argued that",
    choices: [
      ["change should come only through the courts and legislation", "King defended direct action because legal channels had been too slow."],
      ["people have a moral responsibility to disobey unjust laws through nonviolent direct action", "Correct. King distinguished just from unjust laws and defended civil disobedience."],
      ["violent resistance is justified when peaceful methods fail", "King explicitly defended nonviolence."],
      ["civil rights activists should wait until public opinion changed", "King criticized calls to \"wait\" as delaying justice."],
    ],
    answer: "B",
    explanation: "The Letter defends nonviolent civil disobedience and responds to critics who called the Birmingham demonstrations \"unwise and untimely.\"",
    documentIds: ["letter-birmingham-jail"],
  }),
  q({
    id: "us3-18",
    topicId: "usgov-civil-rights",
    difficulty: "medium",
    concept: "Emancipation Proclamation",
    stem: "Which statement most accurately describes the Emancipation Proclamation?",
    choices: [
      ["It abolished slavery throughout the United States.", "Nationwide abolition came with the Thirteenth Amendment in 1865."],
      ["It granted formerly enslaved men the right to vote.", "Voting rights regardless of race came with the Fifteenth Amendment in 1870."],
      ["It was a constitutional amendment ratified by the states.", "It was an executive proclamation issued by President Lincoln."],
      ["It declared enslaved people in states in rebellion to be free, marking a shift toward civil rights.", "Correct. It applied to Confederate states and was followed by the Thirteenth Amendment."],
    ],
    answer: "D",
    explanation: "The course framework describes the Proclamation as freeing enslaved people in states in rebellion, with the Thirteenth Amendment permanently abolishing slavery.",
    documentIds: ["emancipation-proclamation"],
  }),
  q({
    id: "us3-19",
    topicId: "usgov-civil-rights",
    difficulty: "hard",
    concept: "Shaw v. Reno",
    stem: "In Shaw v. Reno (1993), the Supreme Court held that",
    choices: [
      ["congressional districts must contain roughly equal populations", "The one-person, one-vote principle comes from cases following Baker v. Carr."],
      ["redistricting is a political question that courts may not review", "Baker v. Carr (1962) held redistricting claims can be justiciable."],
      ["districts drawn primarily on the basis of race are subject to strict scrutiny under the Equal Protection Clause", "Correct. Race-based districting must be narrowly tailored to a compelling interest."],
      ["partisan gerrymandering claims are always justiciable in federal courts", "In Rucho v. Common Cause (2019), the Court held such claims are nonjusticiable."],
    ],
    answer: "C",
    explanation: "Shaw involved an irregularly shaped majority-minority district in North Carolina. The Court held racial gerrymandering claims can proceed under strict scrutiny.",
    caseIds: ["shaw-v-reno"],
  }),
];
