import { bank } from "./helpers";

const q = bank("usgov", "usgov-u1");

export const usgovU1Questions = [
  q({
    id: "us1-01",
    topicId: "usgov-democratic-ideals",
    difficulty: "medium",
    concept: "Popular sovereignty",
    stimulus: {
      kind: "text",
      text: "\"That to secure these rights, Governments are instituted among Men, deriving their just powers from the consent of the governed.\"",
      source: "Declaration of Independence, 1776",
    },
    stem: "Which democratic principle is most directly expressed in the excerpt?",
    choices: [
      ["Federalism", "Federalism divides power between national and state governments; the excerpt is about where government's authority comes from."],
      ["Checks and balances", "Checks and balances concern how branches limit one another, which the excerpt does not address."],
      ["Popular sovereignty", "Correct. \"Consent of the governed\" means government's legitimate authority comes from the people."],
      ["Judicial review", "Judicial review is the courts' power to invalidate laws, established later in Marbury v. Madison."],
    ],
    answer: "C",
    explanation: "The Declaration grounds government's \"just powers\" in the consent of the people — the definition of popular sovereignty. It pairs this with natural rights and the social contract.",
    documentIds: ["declaration"],
  }),
  q({
    id: "us1-02",
    topicId: "usgov-democratic-ideals",
    difficulty: "medium",
    concept: "Participatory democracy",
    stem: "Citizens in a state collect signatures to place a proposed law on the ballot, and voters approve it in the next election without any action by the state legislature. This scenario best illustrates which model of democracy?",
    choices: [
      ["Elite democracy", "Elite democracy emphasizes the influence of a small, wealthy, educated minority, not broad citizen action."],
      ["Pluralist democracy", "Pluralist democracy centers on organized groups competing for influence; here ordinary voters act directly."],
      ["Representative democracy through elected legislators", "The legislature is bypassed entirely, so the defining feature is not representation."],
      ["Participatory democracy", "Correct. Citizens directly propose and approve law, the hallmark of participatory democracy."],
    ],
    answer: "D",
    explanation: "Ballot initiatives let citizens make policy directly. Participatory democracy emphasizes broad, direct participation like this.",
  }),
  q({
    id: "us1-03",
    topicId: "usgov-democratic-ideals",
    difficulty: "hard",
    concept: "Elite democracy in the Constitution",
    stem: "Which feature of the original Constitution is most often cited as reflecting the elite model of democracy?",
    choices: [
      ["Selection of senators by state legislatures", "Correct. Before the Seventeenth Amendment, senators were chosen by state legislators rather than voters, filtering popular influence through elites."],
      ["Direct election of members of the House of Representatives", "Direct House elections are the most popular (participatory) feature of the original design."],
      ["The First Amendment right to petition the government", "Petitioning supports participatory and pluralist activity, not elite control."],
      ["Equal representation of each state in the Senate", "Equal state representation reflects federalism and the Great Compromise, not elite influence."],
    ],
    answer: "A",
    explanation: "Indirect selection mechanisms — senators chosen by state legislatures and the Electoral College — are classic elite-democracy features because they place decisions in the hands of a smaller, presumably more informed group.",
  }),
  q({
    id: "us1-04",
    topicId: "usgov-articles-convention",
    difficulty: "medium",
    concept: "Weaknesses of the Articles",
    stem: "The Constitution's grant to Congress of the power \"to lay and collect Taxes\" most directly addressed which weakness of the Articles of Confederation?",
    choices: [
      ["The absence of a national court system", "The judiciary was addressed by Article III, not the taxing power."],
      ["The national government could only request money from the states", "Correct. Under the Articles, Congress could requisition funds but had no power to compel payment, leaving it chronically short of revenue."],
      ["The requirement of unanimous consent to amend the Articles", "Article V's amendment process addressed this problem."],
      ["The lack of a single national executive", "Article II created the presidency to address this weakness."],
    ],
    answer: "B",
    explanation: "Without a taxing power, Congress under the Articles could not pay debts or fund an army. The Constitution's taxing power fixed that core weakness.",
    documentIds: ["articles-of-confederation", "constitution"],
  }),
  q({
    id: "us1-05",
    topicId: "usgov-articles-convention",
    difficulty: "easy",
    concept: "Shays' Rebellion",
    stem: "Shays' Rebellion (1786–1787) most directly contributed to which development?",
    choices: [
      ["The adoption of the Bill of Rights", "The Bill of Rights came after ratification as a concession to Anti-Federalists."],
      ["The writing of the Declaration of Independence", "The Declaration was written a decade earlier, in 1776."],
      ["Growing support for a stronger national government and the Constitutional Convention", "Correct. The national government's inability to respond to the uprising convinced many leaders the Articles needed replacing."],
      ["The creation of the first national political parties", "Parties emerged in the 1790s from disputes over Hamilton's policies, not from Shays' Rebellion."],
    ],
    answer: "C",
    explanation: "The rebellion exposed the Articles' weakness: Congress could not raise an army or revenue to restore order. It helped build support for the 1787 convention.",
  }),
  q({
    id: "us1-06",
    topicId: "usgov-articles-convention",
    difficulty: "medium",
    concept: "Great Compromise",
    stem: "The Great (Connecticut) Compromise resolved a dispute at the Constitutional Convention between",
    choices: [
      ["Northern and Southern delegates over how to count enslaved people", "That dispute was resolved by the Three-Fifths Compromise."],
      ["delegates who wanted Congress to choose the president and those who wanted a popular vote", "That dispute produced the Electoral College."],
      ["Federalists and Anti-Federalists over the need for a bill of rights", "That debate occurred during ratification, after the Convention."],
      ["large and small states over representation in Congress", "Correct. The compromise created a House based on population and a Senate with equal state representation."],
    ],
    answer: "D",
    explanation: "Large states backed the Virginia Plan and small states the New Jersey Plan. The bicameral Congress blended the two.",
  }),
  q({
    id: "us1-07",
    topicId: "usgov-ratification",
    difficulty: "medium",
    concept: "Federalist No. 10",
    stimulus: {
      kind: "text",
      text: "\"Extend the sphere, and you take in a greater variety of parties and interests; you make it less probable that a majority of the whole will have a common motive to invade the rights of other citizens.\"",
      source: "James Madison, Federalist No. 10, 1787",
    },
    stem: "Which of the following best summarizes the argument in the excerpt?",
    choices: [
      ["A large republic makes it less likely that a single faction can dominate and oppress others.", "Correct. Madison argues that a large, diverse republic dilutes the power of any single faction."],
      ["States should retain sovereignty to protect citizens from a distant national government.", "This is closer to the Anti-Federalist position in Brutus No. 1."],
      ["A bill of rights is necessary to protect individual liberties from majority factions.", "Madison's argument here relies on the size and diversity of the republic, not a bill of rights."],
      ["Direct democracy is the best way to control the effects of faction.", "Madison argued that pure democracy offers no cure for faction; he favored representation in a large republic."],
    ],
    answer: "A",
    explanation: "Federalist No. 10 argues that the causes of faction can't be removed without destroying liberty, so a large republic should control their effects by multiplying interests.",
    documentIds: ["federalist-10"],
  }),
  q({
    id: "us1-08",
    topicId: "usgov-ratification",
    difficulty: "medium",
    concept: "Brutus No. 1",
    stem: "The author of Brutus No. 1 would most likely have supported which of the following?",
    choices: [
      ["Expanding Congress's power under the Necessary and Proper Clause", "Brutus feared the Necessary and Proper Clause would allow unlimited national power."],
      ["Limiting national power and preserving the authority of state governments", "Correct. Brutus argued that a large national republic would absorb state power and threaten liberty."],
      ["Granting the national government an unlimited power to tax", "Brutus specifically warned against the broad taxing power."],
      ["Creating a large, permanent national army", "Anti-Federalists, including Brutus, opposed standing armies as threats to liberty."],
    ],
    answer: "B",
    explanation: "Brutus No. 1 argued that free republics must be small, that the proposed government's broad clauses would swallow the states, and that power should remain closer to the people.",
    documentIds: ["brutus-1"],
  }),
  q({
    id: "us1-09",
    topicId: "usgov-ratification",
    difficulty: "hard",
    concept: "Bill of Rights as compromise",
    stem: "The addition of the Bill of Rights to the Constitution is best understood as",
    choices: [
      ["a requirement carried over from the Articles of Confederation", "The Articles contained no bill of rights."],
      ["a Federalist plan to expand national power after ratification", "The amendments limited national power; they were not an expansion."],
      ["a concession to Anti-Federalists that helped secure ratification", "Correct. Several states ratified with the expectation that amendments protecting rights would follow."],
      ["a response to the Supreme Court's decision in Marbury v. Madison", "The Bill of Rights was ratified in 1791, twelve years before Marbury."],
    ],
    answer: "C",
    explanation: "Anti-Federalists demanded explicit protections for individual liberties. Madison drafted the amendments in the First Congress, and ten were ratified in 1791.",
  }),
  q({
    id: "us1-10",
    topicId: "usgov-separation-of-powers",
    difficulty: "medium",
    concept: "Federalist No. 51",
    stimulus: {
      kind: "text",
      text: "\"Ambition must be made to counteract ambition. The interest of the man must be connected with the constitutional rights of the place.\"",
      source: "James Madison, Federalist No. 51, 1788",
    },
    stem: "Which constitutional provision best reflects the principle expressed in the excerpt?",
    choices: [
      ["The Tenth Amendment's reservation of powers to the states", "The Tenth Amendment concerns federalism, not competition among branches."],
      ["The Full Faith and Credit Clause", "This clause concerns relations among states."],
      ["The Electoral College", "The Electoral College is a method of selecting the president, not a check between branches."],
      ["The president's veto, which Congress may override by a two-thirds vote", "Correct. The veto and override give each branch a way to resist the other, turning ambition into a check."],
    ],
    answer: "D",
    explanation: "Madison argued each branch needs the constitutional means and personal motive to resist encroachment. The veto/override relationship is a textbook example.",
    documentIds: ["federalist-51"],
  }),
  q({
    id: "us1-11",
    topicId: "usgov-separation-of-powers",
    difficulty: "easy",
    concept: "Checks and balances",
    stem: "Which of the following is an example of the Senate checking the executive branch?",
    choices: [
      ["Rejecting the president's nominee for secretary of defense", "Correct. The Senate's advice-and-consent power over appointments checks the president."],
      ["Voting to impeach the president", "The House impeaches; the Senate conducts the trial."],
      ["Declaring a law unconstitutional", "That is judicial review, a power of the courts."],
      ["Issuing an executive order", "Executive orders are issued by the president."],
    ],
    answer: "A",
    explanation: "Senate confirmation of appointments is one of the most frequently used checks on the executive.",
  }),
  q({
    id: "us1-12",
    topicId: "usgov-separation-of-powers",
    difficulty: "hard",
    concept: "Power of the purse",
    stem: "The president vetoes a bill, and Congress lacks the votes to override. Which action would most likely allow Congress to still shape policy in that area?",
    choices: [
      ["Asking the Supreme Court for an advisory opinion on the veto", "Federal courts do not issue advisory opinions; they decide actual cases."],
      ["Adding funding conditions on the relevant programs in an appropriations bill", "Correct. The power of the purse lets Congress shape policy by conditioning or limiting funding."],
      ["Impeaching the president for issuing the veto", "A veto is a constitutional power, not an impeachable offense."],
      ["Passing a resolution nullifying the veto by simple majority", "Overriding a veto requires two-thirds of both chambers."],
    ],
    answer: "B",
    explanation: "Congress controls appropriations, so it can influence executive policy through funding levels and conditions even without overriding a veto.",
  }),
  q({
    id: "us1-13",
    topicId: "usgov-federalism",
    difficulty: "easy",
    concept: "Concurrent powers",
    stem: "Which of the following is a concurrent power shared by the national and state governments?",
    choices: [
      ["Coining money", "Coining money is an exclusive national power."],
      ["Declaring war", "Only Congress can declare war."],
      ["Borrowing money", "Correct. Both national and state governments can borrow."],
      ["Conducting elections", "Running elections is a reserved state power, though Congress may regulate some aspects of federal elections."],
    ],
    answer: "C",
    explanation: "Concurrent powers — taxing, borrowing, establishing courts, making and enforcing laws — are held independently by both levels of government.",
  }),
  q({
    id: "us1-14",
    topicId: "usgov-federalism",
    difficulty: "medium",
    concept: "McCulloch v. Maryland",
    stem: "In McCulloch v. Maryland (1819), the Supreme Court held that",
    choices: [
      ["states may nullify federal laws they consider unconstitutional", "The Court rejected state authority to interfere with federal institutions."],
      ["Congress's commerce power extends only to economic activity", "That reasoning comes from United States v. Lopez (1995)."],
      ["federal courts may declare acts of Congress unconstitutional", "Judicial review was established in Marbury v. Madison (1803)."],
      ["Congress had implied power to create a national bank, and states could not tax it", "Correct. The Court relied on the Necessary and Proper Clause and the Supremacy Clause."],
    ],
    answer: "D",
    explanation: "McCulloch expanded national power in two ways: it endorsed implied powers under the Necessary and Proper Clause and affirmed national supremacy over conflicting state action.",
    caseIds: ["mcculloch-v-maryland"],
  }),
  q({
    id: "us1-15",
    topicId: "usgov-federalism",
    difficulty: "hard",
    concept: "Federalist No. 39",
    stimulus: {
      kind: "text",
      text: "\"The proposed Constitution, therefore, is, in strictness, neither a national nor a federal Constitution, but a composition of both.\"",
      source: "James Madison, Federalist No. 39, 1788",
    },
    stem: "Which constitutional feature best illustrates the \"federal\" — that is, state-based — element Madison describes?",
    choices: [
      ["Equal representation of each state in the Senate", "Correct. The Senate represents states as equal political units, the federal (confederal) element Madison identified."],
      ["Apportionment of House seats by population", "Representation by population rests on the people as individuals — the national element."],
      ["The Supremacy Clause", "The Supremacy Clause elevates national law, a national feature."],
      ["Congress's power to tax individuals directly", "Direct taxation of individuals operates on the people, a national feature."],
    ],
    answer: "A",
    explanation: "Madison described some features as resting on the people directly (national) and others on the states as equals (federal). The Senate is the clearest federal feature.",
    documentIds: ["federalist-39"],
  }),
  q({
    id: "us1-16",
    topicId: "usgov-federalism-in-practice",
    difficulty: "medium",
    concept: "Block grants",
    stem: "Congress provides states with funding for \"community development\" and allows each state broad discretion in deciding how to spend it. This is an example of",
    choices: [
      ["a categorical grant", "Categorical grants fund specific purposes with detailed conditions."],
      ["a block grant", "Correct. Block grants fund broad policy areas and give states flexibility."],
      ["an unfunded mandate", "Mandates impose requirements; this scenario provides money with discretion."],
      ["a condition of aid", "Conditions of aid attach requirements to funding — the opposite of broad discretion."],
    ],
    answer: "B",
    explanation: "Block grants shift discretion toward states; categorical grants keep more control at the national level.",
  }),
  q({
    id: "us1-17",
    topicId: "usgov-federalism-in-practice",
    difficulty: "hard",
    concept: "United States v. Lopez",
    stem: "Which statement best describes the reasoning of the Supreme Court in United States v. Lopez (1995)?",
    choices: [
      ["The Second Amendment protects an individual right to possess firearms near schools.", "Lopez was not decided on Second Amendment grounds."],
      ["States may not regulate firearms because of the Supremacy Clause.", "Lopez strengthened state authority; it did not restrict state regulation."],
      ["Possessing a gun near a school is not an economic activity that substantially affects interstate commerce, so Congress exceeded its power.", "Correct. The Court held the Gun-Free School Zones Act exceeded the Commerce Clause."],
      ["Congress may attach conditions to federal education funds to regulate guns near schools.", "The law at issue was a direct criminal prohibition, not a funding condition."],
    ],
    answer: "C",
    explanation: "Lopez marked the first time in decades the Court limited Congress's Commerce Clause power, signaling renewed attention to state authority.",
    caseIds: ["united-states-v-lopez"],
  }),
  q({
    id: "us1-18",
    topicId: "usgov-federalism-in-practice",
    difficulty: "medium",
    concept: "Conditions of aid",
    stem: "The national minimum drinking age of 21 was achieved primarily through",
    choices: [
      ["a constitutional amendment", "No amendment set a national drinking age."],
      ["a Supreme Court ruling requiring states to adopt it", "Courts did not order states to set a drinking age."],
      ["an executive order issued by the president", "An executive order cannot impose a drinking age on the states."],
      ["withholding a portion of federal highway funds from states that did not adopt it", "Correct. Congress used conditions of aid, a tool of fiscal federalism."],
    ],
    answer: "D",
    explanation: "Congress can't directly set state drinking ages, but it can attach conditions to federal funds. Every state adopted the age of 21.",
  }),
];
