import { bank } from "./helpers";

const q = bank("usgov", "usgov-u4");

export const usgovU4Questions = [
  q({
    id: "us4-01",
    topicId: "usgov-core-values",
    difficulty: "medium",
    concept: "Free enterprise",
    stimulus: {
      kind: "text",
      text: "\"It is not from the benevolence of the butcher, the brewer, or the baker, that we expect our dinner, but from their regard to their own interest.\"",
      source: "Adam Smith, The Wealth of Nations, 1776",
    },
    stem: "The excerpt most directly supports which core American value?",
    choices: [
      ["Rule of law", "Rule of law concerns everyone being subject to the same laws."],
      ["Free enterprise", "Correct. Smith argues that self-interest in markets produces benefits for others."],
      ["Equality of opportunity", "The excerpt is about markets and self-interest, not fair competition among individuals."],
      ["Limited government", "Related, but the excerpt's focus is on how markets work, not on restraining government."],
    ],
    answer: "B",
    explanation: "The course framework ties free enterprise — self-interest, competition, efficient allocation, limited market regulation — to Adam Smith's Wealth of Nations.",
    documentIds: ["wealth-of-nations"],
  }),
  q({
    id: "us4-02",
    topicId: "usgov-core-values",
    difficulty: "easy",
    concept: "Rule of law",
    stem: "A former governor is prosecuted and convicted for accepting bribes while in office. This outcome best reflects which core value?",
    choices: [
      ["Individualism", "Individualism concerns personal choices shaping one's life."],
      ["Free enterprise", "Free enterprise concerns markets and competition."],
      ["Rule of law", "Correct. Even powerful officials are accountable to the same laws as everyone else."],
      ["Popular sovereignty", "Popular sovereignty concerns the source of government authority."],
    ],
    answer: "C",
    explanation: "Rule of law means no one — including officeholders — is above the law.",
  }),
  q({
    id: "us4-03",
    topicId: "usgov-core-values",
    difficulty: "hard",
    concept: "Interpreting shared values",
    stem: "One senator argues that federal funding for early childhood education promotes equality of opportunity. Another argues the same policy undermines individualism by expanding government's role. Which statement best explains this disagreement?",
    choices: [
      ["Americans generally share core values but interpret and prioritize them differently.", "Correct. Both senators appeal to widely held values but reach opposite conclusions."],
      ["The senators disagree about whether equality of opportunity is a core American value.", "Both accept core values; they disagree about implications."],
      ["One senator rejects the principle of limited government entirely.", "Supporting one program doesn't mean rejecting limited government."],
      ["Core values are only relevant to economic policy.", "Core values shape debates on social and economic issues alike."],
    ],
    answer: "A",
    explanation: "Much of American political debate involves applying shared values — individualism, equality of opportunity, free enterprise — in different ways.",
  }),
  q({
    id: "us4-04",
    topicId: "usgov-socialization",
    difficulty: "medium",
    concept: "Generational effects",
    stem: "Americans who came of age during the Great Depression remained more supportive of government economic programs throughout their lives than later groups did. This is an example of",
    choices: [
      ["a life-cycle effect", "Life-cycle effects come from changing circumstances with age, not a shared formative event."],
      ["political efficacy", "Efficacy is belief in one's ability to influence politics."],
      ["a generational effect", "Correct. A shared formative experience shaped lasting attitudes of an age cohort."],
      ["selective exposure", "Selective exposure concerns choosing media consistent with existing views."],
    ],
    answer: "C",
    explanation: "Generational effects arise when major events shape the attitudes of people who experience them during formative years.",
  }),
  q({
    id: "us4-05",
    topicId: "usgov-socialization",
    difficulty: "medium",
    concept: "Life-cycle effects",
    stem: "As a voter ages, buys a home, and begins paying property taxes, she becomes more concerned about tax rates than she was as a college student. This change best illustrates",
    choices: [
      ["a life-cycle effect", "Correct. Her priorities changed with her stage of life and circumstances."],
      ["a generational effect", "Nothing suggests a shared formative event for her cohort."],
      ["political realignment", "Realignment is a durable shift in party coalitions."],
      ["globalization", "Globalization concerns international interconnectedness."],
    ],
    answer: "A",
    explanation: "Life-cycle effects describe how attitudes and interests shift as people move through stages of life.",
  }),
  q({
    id: "us4-06",
    topicId: "usgov-socialization",
    difficulty: "easy",
    concept: "Agents of socialization",
    stem: "Research on political socialization generally finds that the most influential early source of a person's party identification is",
    choices: [
      ["the news media", "Media grows more influential later in life."],
      ["the family", "Correct. Children often adopt their parents' party identification."],
      ["peer groups", "Peers become more influential in adolescence and adulthood."],
      ["elected officials", "Officials are not a primary agent of early socialization."],
    ],
    answer: "B",
    explanation: "Family transmission of partisanship is strongest when parents share a party and discuss politics frequently.",
  }),
  q({
    id: "us4-07",
    topicId: "usgov-public-opinion-polling",
    difficulty: "medium",
    concept: "Margin of error",
    stimulus: {
      kind: "table",
      title: "Statewide Senate Poll (hypothetical)",
      headers: ["Candidate", "Support"],
      rows: [
        ["Candidate A", "47%"],
        ["Candidate B", "44%"],
        ["Undecided", "9%"],
      ],
      source: "Random sample of 800 likely voters. Margin of error ±4 percentage points.",
      note: "Hypothetical data for practice.",
    },
    stem: "Which conclusion is best supported by the poll?",
    choices: [
      ["Candidate A will win the election.", "Polls measure current opinion; they can't guarantee outcomes, and the lead is within the margin of error."],
      ["The race is statistically too close to call.", "Correct. A 3-point lead is smaller than the ±4 margin of error."],
      ["Candidate B's supporters are less likely to vote.", "The poll provides no information about turnout likelihood by candidate."],
      ["The poll is unreliable because the sample is too small.", "A random sample of 800 is typical for statewide polls."],
    ],
    answer: "B",
    explanation: "When the difference between two candidates is smaller than the margin of error, the poll can't confidently identify a leader.",
  }),
  q({
    id: "us4-08",
    topicId: "usgov-public-opinion-polling",
    difficulty: "medium",
    concept: "Poll reliability",
    stem: "Which of the following would most undermine the reliability of a poll?",
    choices: [
      ["Using a random sample of 1,000 adults", "A random sample of this size is standard and reliable."],
      ["Reporting the margin of error", "Reporting the margin of error increases transparency."],
      ["Weighting results to match the population's demographics", "Weighting helps correct for sampling imbalances."],
      ["Inviting anyone who visits a website to respond", "Correct. Opt-in samples are self-selected rather than random, so results can't be generalized."],
    ],
    answer: "D",
    explanation: "Reliable polls depend on random, representative samples. Self-selected online polls fail this test regardless of size.",
  }),
  q({
    id: "us4-09",
    topicId: "usgov-public-opinion-polling",
    difficulty: "easy",
    concept: "Types of polls",
    stem: "A campaign surveys voters every week using the same questions to see how support for its candidate changes over time. This is an example of a",
    choices: [
      ["tracking poll", "Correct. Tracking polls measure changes in opinion over time."],
      ["benchmark poll", "A benchmark poll establishes a starting point at the beginning of a campaign."],
      ["exit poll", "Exit polls survey voters as they leave polling places."],
      ["push poll", "Push polls are persuasion tactics disguised as surveys."],
    ],
    answer: "A",
    explanation: "Tracking polls repeat questions over time to follow trends in voter opinion.",
  }),
  q({
    id: "us4-10",
    topicId: "usgov-ideologies",
    difficulty: "medium",
    concept: "Libertarianism",
    stem: "Which position is most consistent with libertarian ideology?",
    choices: [
      ["Increasing regulation of business while reducing government involvement in personal behavior", "Increasing business regulation is inconsistent with libertarian views."],
      ["Expanding social programs funded by higher taxes on the wealthy", "This is associated with modern liberalism."],
      ["Minimizing government involvement in both the economy and personal decisions", "Correct. Libertarians favor minimal government across both dimensions."],
      ["Using government to promote traditional social values while cutting taxes", "This combination is associated with social conservatism."],
    ],
    answer: "C",
    explanation: "Libertarians support free markets and personal freedom, opposing most government regulation in both areas.",
  }),
  q({
    id: "us4-11",
    topicId: "usgov-ideologies",
    difficulty: "medium",
    concept: "Conservative ideology",
    stem: "A political candidate calls for lower corporate taxes, fewer business regulations, and reduced federal spending on social programs. The candidate's positions are most consistent with",
    choices: [
      ["modern American liberalism", "Liberals generally support more regulation and social spending."],
      ["socialism", "Socialism favors extensive government involvement in the economy."],
      ["populism", "Populism is an anti-elite style that can take many ideological forms."],
      ["modern American conservatism", "Correct. Conservatives generally favor free markets, lower taxes, and limited economic regulation."],
    ],
    answer: "D",
    explanation: "On economic issues, conservatives generally favor a smaller government role; liberals favor a larger one.",
  }),
  q({
    id: "us4-12",
    topicId: "usgov-ideologies",
    difficulty: "hard",
    concept: "Ideology and the role of government",
    stimulus: {
      kind: "bar",
      title: "Share Saying \"Government Should Do More to Solve Problems\" (hypothetical)",
      unit: "%",
      series: [
        { label: "Liberals", value: 78 },
        { label: "Moderates", value: 55 },
        { label: "Conservatives", value: 24 },
        { label: "Libertarians", value: 12 },
      ],
      note: "Hypothetical data for practice.",
    },
    stem: "Which statement is best supported by the data and consistent with the ideological positions described in the course?",
    choices: [
      ["Support for an active government declines as respondents move from liberal to conservative and libertarian.", "Correct. The data follows the expected pattern of ideological views on government's role."],
      ["Moderates are more supportive of government action than liberals.", "Moderates (55%) are less supportive than liberals (78%)."],
      ["Conservatives and liberals have nearly identical views about government's role.", "The 54-point gap shows sharp differences."],
      ["Libertarians are the group most likely to favor government action.", "Libertarians are the least likely (12%)."],
    ],
    answer: "A",
    explanation: "Liberals generally favor a larger government role; conservatives and especially libertarians favor a smaller one. The data mirrors that pattern.",
  }),
  q({
    id: "us4-13",
    topicId: "usgov-ideology-policy",
    difficulty: "easy",
    concept: "Monetary policy",
    stem: "Which action is an example of monetary policy?",
    choices: [
      ["Congress passes a bill cutting income tax rates.", "Changing taxes is fiscal policy."],
      ["The Federal Reserve lowers its target interest rate.", "Correct. The Federal Reserve conducts monetary policy through interest rates and the money supply."],
      ["The president proposes a budget increasing infrastructure spending.", "Spending proposals are fiscal policy."],
      ["A state legislature raises its sales tax.", "State taxes are part of state fiscal policy."],
    ],
    answer: "B",
    explanation: "Monetary policy is set by the independent Federal Reserve; fiscal policy is set by Congress and the president.",
  }),
  q({
    id: "us4-14",
    topicId: "usgov-ideology-policy",
    difficulty: "medium",
    concept: "Keynesian economics",
    stem: "During a recession, a policymaker argues that the government should increase spending on public works, even if it increases the deficit, to boost demand and employment. This argument reflects",
    choices: [
      ["supply-side economics", "Supply-side economics emphasizes tax cuts and deregulation to boost production."],
      ["monetary policy", "Public works spending is fiscal, not monetary."],
      ["Keynesian economics", "Correct. Keynesians favor government spending to stimulate demand during downturns."],
      ["laissez-faire economics", "Laissez-faire opposes government intervention in the economy."],
    ],
    answer: "C",
    explanation: "Keynesian theory holds that government spending can offset falling private demand during recessions.",
  }),
  q({
    id: "us4-15",
    topicId: "usgov-ideology-policy",
    difficulty: "medium",
    concept: "Supply-side economics",
    stem: "Which policy is most consistent with supply-side economics?",
    choices: [
      ["Expanding unemployment benefits during a recession", "This is associated with Keynesian demand-side policy."],
      ["Raising the minimum wage to increase consumer spending", "This is a demand-side approach."],
      ["Increasing government purchases of goods and services", "This is Keynesian stimulus."],
      ["Cutting taxes on business investment and reducing regulations", "Correct. Supply-side economics aims to boost production and investment."],
    ],
    answer: "D",
    explanation: "Supply-siders argue lower taxes and less regulation encourage businesses to invest and expand, spurring growth.",
  }),
  q({
    id: "us4-16",
    topicId: "usgov-ideology-policy",
    difficulty: "hard",
    concept: "Federal Reserve independence",
    stem: "Which of the following best explains why the Federal Reserve was designed to be independent of direct control by elected officials?",
    choices: [
      ["To insulate monetary policy from short-term electoral pressures", "Correct. Independence lets the Fed make unpopular decisions, like raising rates to fight inflation."],
      ["To give the Supreme Court authority over interest rates", "The Court doesn't set monetary policy."],
      ["To allow states to set their own interest rates", "Monetary policy is national."],
      ["To ensure fiscal policy is set by unelected officials", "Fiscal policy remains with Congress and the president."],
    ],
    answer: "A",
    explanation: "Elected officials may prefer low rates before elections even when inflation is rising; Fed independence is meant to guard against that pressure.",
  }),
];
