import type { CaseCluster, SupremeCourtCase } from "./types";

/**
 * Supreme Court case database.
 *
 * `required: true` marks the 14 cases required by the AP U.S. Government and
 * Politics CED (verified September 2026). Supplemental cases are common
 * SCOTUS Comparison material or are discussed in the framework without being
 * on the required list.
 */
export const CASES: SupremeCourtCase[] = [
  // ------------------------------------------------------------ Required
  {
    id: "marbury-v-madison",
    name: "Marbury v. Madison",
    shortName: "Marbury",
    year: 1803,
    required: true,
    vote: "4–0",
    amendments: [],
    topics: ["judicial review", "separation of powers", "Article III"],
    unitId: "usgov-u2",
    cluster: "judicial-power",
    issue: "Does the Supreme Court have the power to declare an act of Congress unconstitutional?",
    background:
      "In the final days of his presidency, John Adams appointed William Marbury as a justice of the peace. The commission was signed but not delivered. When Thomas Jefferson took office, Secretary of State James Madison refused to deliver it. Marbury asked the Supreme Court to issue a writ of mandamus ordering delivery, relying on a provision of the Judiciary Act of 1789.",
    decision:
      "Chief Justice John Marshall held that Marbury had a right to the commission, but that the provision of the Judiciary Act allowing him to seek mandamus directly in the Supreme Court was unconstitutional because it expanded the Court's original jurisdiction beyond what Article III allows.",
    principle:
      "Established judicial review — the power of federal courts to declare legislative and executive acts unconstitutional.",
    apRelevance:
      "The foundation of the judiciary's role in checks and balances. Pair it with Federalist No. 78 in essays on judicial power, and use it to explain how courts check Congress and the president.",
    related: [
      { id: "mcculloch-v-maryland", relation: "Marshall Court case strengthening national institutions" },
      { id: "dobbs-v-jackson", relation: "Modern example of the Court's power to reshape policy" },
    ],
  },
  {
    id: "mcculloch-v-maryland",
    name: "McCulloch v. Maryland",
    shortName: "McCulloch",
    year: 1819,
    required: true,
    vote: "7–0",
    amendments: ["10th"],
    topics: ["federalism", "implied powers", "Necessary and Proper Clause", "Supremacy Clause"],
    unitId: "usgov-u1",
    cluster: "federalism",
    issue: "Does Congress have the power to create a national bank, and may a state tax it?",
    background:
      "Congress chartered the Second Bank of the United States. Maryland imposed a tax on notes issued by banks not chartered by the state. James McCulloch, cashier of the Baltimore branch, refused to pay.",
    decision:
      "The Court unanimously held that Congress had the implied power to create the bank under the Necessary and Proper Clause, and that Maryland could not tax it because, under the Supremacy Clause, states cannot interfere with legitimate federal institutions. Marshall wrote that \"the power to tax involves the power to destroy.\"",
    principle: "Implied powers and national supremacy: Congress may use means reasonably related to its enumerated powers, and valid federal law prevails over conflicting state action.",
    apRelevance:
      "The anchor case for expansive national power in federalism questions. Contrast it with United States v. Lopez. Connects to the Federalist–Anti-Federalist debate over the Necessary and Proper Clause (Brutus No. 1).",
    related: [
      { id: "united-states-v-lopez", relation: "Contrast: Lopez limited congressional power" },
      { id: "gibbons-v-ogden", relation: "Marshall Court case expanding the commerce power" },
      { id: "marbury-v-madison", relation: "Marshall Court case establishing judicial review" },
    ],
  },
  {
    id: "schenck-v-united-states",
    name: "Schenck v. United States",
    shortName: "Schenck",
    year: 1919,
    required: true,
    vote: "9–0",
    amendments: ["1st"],
    topics: ["free speech", "clear and present danger", "national security"],
    unitId: "usgov-u3",
    cluster: "speech-press",
    issue: "Does the First Amendment protect speech that urges resistance to the military draft during wartime?",
    background:
      "During World War I, Charles Schenck, general secretary of the Socialist Party, distributed leaflets urging men to resist the draft. He was convicted under the Espionage Act of 1917.",
    decision:
      "The Court unanimously upheld the conviction. Justice Oliver Wendell Holmes wrote that speech may be restricted when it creates a \"clear and present danger\" of bringing about harms Congress has a right to prevent, especially in wartime.",
    principle: "Speech is not absolutely protected; it may be limited when it presents a clear and present danger. (Later replaced by the Brandenburg imminent lawless action test.)",
    apRelevance:
      "A required case for limits on free speech and the balance between liberty and order. Frequently paired with Tinker or Brandenburg in SCOTUS Comparison questions.",
    related: [
      { id: "brandenburg-v-ohio", relation: "Replaced by the imminent lawless action test" },
      { id: "nyt-v-united-states", relation: "National security versus expression" },
      { id: "tinker-v-des-moines", relation: "Another test for when speech may be limited" },
    ],
  },
  {
    id: "brown-v-board",
    name: "Brown v. Board of Education",
    shortName: "Brown",
    year: 1954,
    required: true,
    vote: "9–0",
    amendments: ["14th"],
    topics: ["equal protection", "segregation", "civil rights", "precedent"],
    unitId: "usgov-u3",
    cluster: "equal-protection",
    issue: "Does racial segregation of children in public schools violate the Equal Protection Clause of the Fourteenth Amendment?",
    background:
      "Linda Brown, a Black student in Topeka, Kansas, was denied admission to a nearby white school. The NAACP, with Thurgood Marshall as lead counsel, combined her case with others challenging segregated schools.",
    decision:
      "A unanimous Court, led by Chief Justice Earl Warren, held that \"separate educational facilities are inherently unequal\" and violate the Equal Protection Clause, overturning Plessy v. Ferguson's \"separate but equal\" doctrine in public education.",
    principle: "State-mandated racial segregation in public education violates equal protection.",
    apRelevance:
      "Illustrates the Court protecting minority rights, overturning precedent, and relying on the executive to enforce rulings. Pairs with the Letter from Birmingham Jail and the Civil Rights Act of 1964 in essays on civil rights.",
    related: [
      { id: "plessy-v-ferguson", relation: "Overturned in public education" },
      { id: "shaw-v-reno", relation: "Later equal protection case on race and districting" },
      { id: "sffa-v-harvard", relation: "Equal protection and race-conscious admissions" },
      { id: "dobbs-v-jackson", relation: "Another landmark overturning of precedent" },
    ],
  },
  {
    id: "baker-v-carr",
    name: "Baker v. Carr",
    shortName: "Baker",
    year: 1962,
    required: true,
    vote: "6–2",
    amendments: ["14th"],
    topics: ["redistricting", "one person one vote", "political question", "equal protection"],
    unitId: "usgov-u2",
    cluster: "elections",
    issue: "Can federal courts hear challenges to the apportionment of state legislative districts?",
    background:
      "Tennessee had not redrawn its state legislative districts since 1901, despite major population shifts toward cities. Charles Baker, an urban voter, argued that his vote was diluted relative to rural voters.",
    decision:
      "The Court held that redistricting challenges are justiciable — they are not \"political questions\" beyond the courts' reach — and may be heard under the Equal Protection Clause.",
    principle: "Opened the door to the \"one person, one vote\" principle requiring districts of roughly equal population.",
    apRelevance:
      "Required for Unit 2 content on congressional representation and redistricting. Often compared with Shaw v. Reno and the non-required Rucho v. Common Cause.",
    related: [
      { id: "reynolds-v-sims", relation: "Applied one person, one vote to state legislatures" },
      { id: "shaw-v-reno", relation: "Redistricting and equal protection" },
      { id: "rucho-v-common-cause", relation: "Contrast: partisan gerrymandering held nonjusticiable" },
    ],
  },
  {
    id: "engel-v-vitale",
    name: "Engel v. Vitale",
    shortName: "Engel",
    year: 1962,
    required: true,
    vote: "6–1",
    amendments: ["1st", "14th"],
    topics: ["Establishment Clause", "school prayer", "freedom of religion"],
    unitId: "usgov-u3",
    cluster: "religion",
    issue: "Does a state-sponsored, nondenominational prayer in public schools violate the Establishment Clause?",
    background:
      "The New York State Board of Regents wrote a short, nondenominational prayer and recommended that public schools begin each day with it. Participation was voluntary. Parents challenged the practice.",
    decision:
      "The Court held that government-directed prayer in public schools violates the Establishment Clause, even if the prayer is nondenominational and participation is voluntary.",
    principle: "Government may not compose or sponsor official prayers in public schools.",
    apRelevance:
      "The required Establishment Clause case. Frequently paired in SCOTUS Comparison questions with school prayer or religious display cases.",
    related: [
      { id: "wisconsin-v-yoder", relation: "The other religion clause: free exercise" },
      { id: "kennedy-v-bremerton", relation: "Later case on prayer and public schools" },
    ],
  },
  {
    id: "gideon-v-wainwright",
    name: "Gideon v. Wainwright",
    shortName: "Gideon",
    year: 1963,
    required: true,
    vote: "9–0",
    amendments: ["6th", "14th"],
    topics: ["right to counsel", "selective incorporation", "rights of the accused"],
    unitId: "usgov-u3",
    cluster: "accused",
    issue: "Does the Sixth Amendment right to counsel apply to state criminal defendants who cannot afford a lawyer?",
    background:
      "Clarence Earl Gideon was charged with breaking and entering in Florida, a felony. Florida provided counsel only in capital cases, so his request for a lawyer was denied. He represented himself, was convicted, and petitioned the Supreme Court from prison.",
    decision:
      "The Court unanimously held that the right to counsel is a fundamental right incorporated against the states through the Fourteenth Amendment's Due Process Clause. States must provide attorneys to defendants in felony cases who cannot afford them.",
    principle: "Selective incorporation of the Sixth Amendment right to counsel.",
    apRelevance:
      "Required example of selective incorporation and rights of the accused. Shows how an individual petition can reshape criminal justice nationwide.",
    related: [
      { id: "mapp-v-ohio", relation: "Incorporation of criminal procedure rights" },
      { id: "miranda-v-arizona", relation: "Rights of suspects during interrogation" },
      { id: "mcdonald-v-chicago", relation: "Another selective incorporation case" },
    ],
  },
  {
    id: "tinker-v-des-moines",
    name: "Tinker v. Des Moines Independent Community School District",
    shortName: "Tinker",
    year: 1969,
    required: true,
    vote: "7–2",
    amendments: ["1st", "14th"],
    topics: ["symbolic speech", "student speech", "free speech"],
    unitId: "usgov-u3",
    cluster: "speech-press",
    issue: "Does a public school's ban on wearing armbands in protest violate students' free speech rights?",
    background:
      "Students John and Mary Beth Tinker and Christopher Eckhardt wore black armbands to school to protest the Vietnam War. They were suspended under a policy adopted to prevent the protest.",
    decision:
      "The Court held that students do not \"shed their constitutional rights to freedom of speech or expression at the schoolhouse gate.\" The armbands were symbolic speech, and the school had not shown that they would substantially disrupt school activities.",
    principle: "Symbolic student speech is protected unless it causes a substantial disruption of the educational process.",
    apRelevance:
      "The required case on student and symbolic speech. A top candidate for SCOTUS Comparison with Morse v. Frederick or Texas v. Johnson.",
    related: [
      { id: "morse-v-frederick", relation: "Narrowed student speech protections" },
      { id: "texas-v-johnson", relation: "Symbolic speech: flag burning" },
      { id: "schenck-v-united-states", relation: "Earlier limit on speech" },
    ],
  },
  {
    id: "nyt-v-united-states",
    name: "New York Times Co. v. United States",
    shortName: "NYT v. U.S.",
    year: 1971,
    required: true,
    vote: "6–3",
    amendments: ["1st"],
    topics: ["freedom of the press", "prior restraint", "national security", "Pentagon Papers"],
    unitId: "usgov-u3",
    cluster: "speech-press",
    issue: "Can the government prevent newspapers from publishing classified information in the name of national security?",
    background:
      "Daniel Ellsberg leaked a classified Defense Department history of U.S. involvement in Vietnam — the Pentagon Papers — to the New York Times and the Washington Post. The Nixon administration sought injunctions to stop publication.",
    decision:
      "In a brief per curiam opinion, the Court ruled 6–3 that the government had not met the heavy burden required to justify prior restraint.",
    principle: "Prior restraint of the press carries a heavy presumption against its constitutionality.",
    apRelevance:
      "The required freedom-of-the-press case. Useful for questions balancing liberty and national security and for the media's watchdog role.",
    related: [
      { id: "schenck-v-united-states", relation: "National security and expression" },
      { id: "tinker-v-des-moines", relation: "First Amendment expression" },
    ],
  },
  {
    id: "wisconsin-v-yoder",
    name: "Wisconsin v. Yoder",
    shortName: "Yoder",
    year: 1972,
    required: true,
    amendments: ["1st", "14th"],
    topics: ["Free Exercise Clause", "compulsory education", "freedom of religion"],
    unitId: "usgov-u3",
    cluster: "religion",
    issue: "Does a state law requiring school attendance until age 16 violate the free exercise rights of Amish parents?",
    background:
      "Jonas Yoder and other Amish parents in Wisconsin refused to send their children to school after eighth grade, arguing that high school would undermine their religious way of life. They were convicted under the state's compulsory attendance law.",
    decision:
      "The Court ruled for the Amish families, holding that the state's interest in two additional years of compulsory education did not outweigh the parents' right to the free exercise of religion.",
    principle: "The Free Exercise Clause can require exemptions from generally applicable laws when the state's interest does not outweigh the burden on religious practice.",
    apRelevance:
      "The required Free Exercise case. Contrast with Engel (Establishment Clause) to show the two religion clauses.",
    related: [{ id: "engel-v-vitale", relation: "The other religion clause: establishment" }],
  },
  {
    id: "shaw-v-reno",
    name: "Shaw v. Reno",
    shortName: "Shaw",
    year: 1993,
    required: true,
    vote: "5–4",
    amendments: ["14th"],
    topics: ["racial gerrymandering", "majority-minority districts", "equal protection", "redistricting"],
    unitId: "usgov-u2",
    cluster: "elections",
    issue: "Does a redistricting plan drawn primarily on the basis of race violate the Equal Protection Clause?",
    background:
      "After the 1990 census, North Carolina created a second majority-Black congressional district. District 12 was extremely irregular in shape, winding along an interstate highway. White voters challenged the plan.",
    decision:
      "The Court held that a redistricting plan so irregular that it can only be understood as an effort to separate voters by race is subject to strict scrutiny under the Equal Protection Clause.",
    principle: "Race-based districting must be narrowly tailored to a compelling government interest.",
    apRelevance:
      "Required for Unit 2 (congressional representation) and connected to civil rights content. Often compared with Baker v. Carr.",
    related: [
      { id: "baker-v-carr", relation: "Redistricting is justiciable" },
      { id: "brown-v-board", relation: "Equal protection and race" },
      { id: "rucho-v-common-cause", relation: "Partisan (not racial) gerrymandering" },
    ],
  },
  {
    id: "united-states-v-lopez",
    name: "United States v. Lopez",
    shortName: "Lopez",
    year: 1995,
    required: true,
    vote: "5–4",
    amendments: ["10th"],
    topics: ["federalism", "Commerce Clause", "limits on congressional power"],
    unitId: "usgov-u1",
    cluster: "federalism",
    issue: "Does the Gun-Free School Zones Act of 1990 exceed Congress's power under the Commerce Clause?",
    background:
      "Alfonso Lopez Jr., a high school senior in San Antonio, brought a handgun to school and was charged under the federal Gun-Free School Zones Act, which made it a crime to possess a firearm in a school zone.",
    decision:
      "The Court held that possessing a gun near a school is not an economic activity that substantially affects interstate commerce, so Congress exceeded its Commerce Clause authority.",
    principle: "Congress's commerce power has limits; some matters are reserved to the states.",
    apRelevance:
      "The required case for limits on federal power. Contrast with McCulloch in federalism essays and SCOTUS Comparison questions.",
    related: [
      { id: "mcculloch-v-maryland", relation: "Contrast: McCulloch expanded national power" },
      { id: "gibbons-v-ogden", relation: "Early broad reading of the commerce power" },
    ],
  },
  {
    id: "mcdonald-v-chicago",
    name: "McDonald v. Chicago",
    shortName: "McDonald",
    year: 2010,
    required: true,
    vote: "5–4",
    amendments: ["2nd", "14th"],
    topics: ["Second Amendment", "selective incorporation", "due process"],
    unitId: "usgov-u3",
    cluster: "incorporation",
    issue: "Does the Second Amendment right to keep and bear arms apply to state and local governments?",
    background:
      "After District of Columbia v. Heller (2008) recognized an individual right to possess a handgun for self-defense in the home, Otis McDonald, a Chicago resident, challenged the city's handgun ban.",
    decision:
      "The Court held that the Second Amendment right is incorporated against the states through the Fourteenth Amendment's Due Process Clause, and struck down the ban.",
    principle: "Selective incorporation of the Second Amendment.",
    apRelevance:
      "The required selective incorporation case. Use it to explain how the Fourteenth Amendment applies the Bill of Rights to the states.",
    related: [
      { id: "dc-v-heller", relation: "Built on Heller's individual-right holding" },
      { id: "gideon-v-wainwright", relation: "Another selective incorporation case" },
    ],
  },
  {
    id: "citizens-united-v-fec",
    name: "Citizens United v. Federal Election Commission",
    shortName: "Citizens United",
    year: 2010,
    required: true,
    vote: "5–4",
    amendments: ["1st"],
    topics: ["campaign finance", "free speech", "independent expenditures", "super PACs"],
    unitId: "usgov-u5",
    cluster: "elections",
    issue: "Can the government restrict independent political expenditures by corporations and unions?",
    background:
      "Citizens United, a conservative nonprofit, sought to air and advertise a film critical of Hillary Clinton close to the 2008 primaries. Federal law (BCRA) restricted corporate-funded \"electioneering communications\" shortly before elections.",
    decision:
      "The Court held that political spending is a form of protected speech and that the government may not ban independent expenditures by corporations and unions.",
    principle: "Independent political expenditures are protected by the First Amendment; limits on direct contributions to candidates remain.",
    apRelevance:
      "The required campaign finance case. Central to debates about free speech versus political equality and to the rise of super PACs.",
    related: [{ id: "buckley-v-valeo", relation: "Earlier ruling treating spending as speech" }],
  },

  // ------------------------------------------------------------ Supplemental
  {
    id: "gibbons-v-ogden",
    name: "Gibbons v. Ogden",
    shortName: "Gibbons",
    year: 1824,
    required: false,
    vote: "6–0",
    amendments: [],
    topics: ["Commerce Clause", "federalism"],
    unitId: "usgov-u1",
    cluster: "federalism",
    issue: "Can a state grant a monopoly over navigation on interstate waters that conflicts with a federal license?",
    background:
      "New York granted Aaron Ogden a monopoly to operate steamboats between New York and New Jersey. Thomas Gibbons operated competing boats under a federal coasting license.",
    decision:
      "The Court held that commerce includes navigation and that Congress's power to regulate interstate commerce overrode the conflicting state monopoly.",
    principle: "A broad definition of interstate commerce and national supremacy over conflicting state regulation.",
    apRelevance: "Useful supplemental evidence on the growth of national power under the Commerce Clause.",
    related: [
      { id: "mcculloch-v-maryland", relation: "Marshall Court expansion of national power" },
      { id: "united-states-v-lopez", relation: "Later limit on the commerce power" },
    ],
  },
  {
    id: "plessy-v-ferguson",
    name: "Plessy v. Ferguson",
    shortName: "Plessy",
    year: 1896,
    required: false,
    vote: "7–1",
    amendments: ["14th"],
    topics: ["segregation", "separate but equal", "equal protection"],
    unitId: "usgov-u3",
    cluster: "equal-protection",
    issue: "Does a state law requiring racially segregated railroad cars violate the Equal Protection Clause?",
    background:
      "Homer Plessy, who was of mixed race, sat in a whites-only railroad car in Louisiana in a planned challenge to the state's Separate Car Act and was arrested.",
    decision:
      "The Court upheld the law under the doctrine of \"separate but equal.\" Justice John Marshall Harlan dissented, arguing that the Constitution is \"color-blind.\"",
    principle: "Legitimized state-mandated segregation until it was rejected in public education by Brown v. Board.",
    apRelevance: "The course framework describes rights restricted by \"separate but equal\" holdings; Plessy is the key example to contrast with Brown.",
    related: [{ id: "brown-v-board", relation: "Overturned in public education by Brown" }],
  },
  {
    id: "mapp-v-ohio",
    name: "Mapp v. Ohio",
    shortName: "Mapp",
    year: 1961,
    required: false,
    vote: "6–3",
    amendments: ["4th", "14th"],
    topics: ["exclusionary rule", "search and seizure", "selective incorporation"],
    unitId: "usgov-u3",
    cluster: "accused",
    issue: "May evidence obtained through an unconstitutional search be used in a state criminal trial?",
    background:
      "Police in Cleveland forcibly entered Dollree Mapp's home without a valid warrant while searching for a suspect and found materials that led to her conviction.",
    decision: "The Court held that the exclusionary rule applies to the states through the Fourteenth Amendment.",
    principle: "Illegally obtained evidence is generally inadmissible in state and federal courts.",
    apRelevance: "Common SCOTUS Comparison partner for Gideon (both incorporate criminal procedure protections).",
    related: [
      { id: "gideon-v-wainwright", relation: "Incorporation of criminal procedure rights" },
      { id: "miranda-v-arizona", relation: "Rights of the accused" },
    ],
  },
  {
    id: "miranda-v-arizona",
    name: "Miranda v. Arizona",
    shortName: "Miranda",
    year: 1966,
    required: false,
    vote: "5–4",
    amendments: ["5th", "6th", "14th"],
    topics: ["self-incrimination", "rights of the accused", "police interrogation"],
    unitId: "usgov-u3",
    cluster: "accused",
    issue: "Must police inform suspects of their rights before custodial interrogation?",
    background: "Ernesto Miranda confessed during police interrogation without being told of his right to remain silent or to have an attorney.",
    decision:
      "The Court held that statements made during custodial interrogation are inadmissible unless suspects are first informed of their rights, including the right to remain silent and to have an attorney.",
    principle: "Procedural safeguards protect the Fifth Amendment privilege against self-incrimination.",
    apRelevance: "Supplemental evidence on rights of the accused and the balance between liberty and order.",
    related: [
      { id: "gideon-v-wainwright", relation: "Right to counsel" },
      { id: "mapp-v-ohio", relation: "Rights of the accused" },
    ],
  },
  {
    id: "griswold-v-connecticut",
    name: "Griswold v. Connecticut",
    shortName: "Griswold",
    year: 1965,
    required: false,
    requiredNote: "Discussed in the CED's due process and privacy topic.",
    vote: "7–2",
    amendments: ["1st", "3rd", "4th", "5th", "9th", "14th"],
    topics: ["right to privacy", "due process"],
    unitId: "usgov-u3",
    cluster: "privacy",
    issue: "Does the Constitution protect a right to privacy that prevents a state from banning contraceptives for married couples?",
    background: "Estelle Griswold, of Planned Parenthood, was convicted for providing contraceptive information to married couples in violation of Connecticut law.",
    decision:
      "The Court struck down the law, finding a right to marital privacy implied by several amendments' \"penumbras\" and by due process.",
    principle: "Recognized an implied constitutional right to privacy.",
    apRelevance: "Foundation for later privacy cases; shows the Court recognizing unenumerated rights.",
    related: [
      { id: "roe-v-wade", relation: "Extended the privacy right" },
      { id: "dobbs-v-jackson", relation: "Later limited the privacy doctrine" },
    ],
  },
  {
    id: "roe-v-wade",
    name: "Roe v. Wade",
    shortName: "Roe",
    year: 1973,
    required: false,
    requiredNote: "Removed from the required list after Dobbs (2022); still discussed in the CED's privacy topic.",
    vote: "7–2",
    amendments: ["14th"],
    topics: ["right to privacy", "due process", "abortion"],
    unitId: "usgov-u3",
    cluster: "privacy",
    issue: "Does the right to privacy protect a woman's decision to have an abortion?",
    background: "\"Jane Roe\" (Norma McCorvey) challenged a Texas law banning most abortions.",
    decision:
      "The Court held that the right to privacy under the Due Process Clause extends to abortion decisions, subject to state interests that increased over the course of pregnancy.",
    principle: "Extended the privacy right to abortion; overturned in 2022 by Dobbs.",
    apRelevance: "No longer required, but useful for explaining precedent, due process, and how Dobbs changed policy.",
    related: [
      { id: "griswold-v-connecticut", relation: "Built on the privacy right" },
      { id: "dobbs-v-jackson", relation: "Overturned by Dobbs" },
    ],
  },
  {
    id: "dobbs-v-jackson",
    name: "Dobbs v. Jackson Women's Health Organization",
    shortName: "Dobbs",
    year: 2022,
    required: false,
    requiredNote: "Discussed in the CED's due process and privacy topic.",
    vote: "6–3",
    amendments: ["14th"],
    topics: ["due process", "abortion", "precedent", "federalism"],
    unitId: "usgov-u3",
    cluster: "privacy",
    issue: "Does the Constitution confer a right to abortion?",
    background: "Mississippi banned most abortions after 15 weeks of pregnancy. Jackson Women's Health Organization challenged the law.",
    decision:
      "The Court upheld the Mississippi law and overturned Roe v. Wade and Planned Parenthood v. Casey, holding that the Constitution does not confer a right to abortion and returning the issue to elected officials.",
    principle: "Overturned precedent and shifted abortion policy to the states and Congress.",
    apRelevance: "Illustrates judicial review, the limits of stare decisis, and federalism's effect on policy variation.",
    related: [
      { id: "roe-v-wade", relation: "Overturned Roe" },
      { id: "brown-v-board", relation: "Another landmark overturning of precedent" },
      { id: "griswold-v-connecticut", relation: "Privacy doctrine" },
    ],
  },
  {
    id: "dc-v-heller",
    name: "District of Columbia v. Heller",
    shortName: "Heller",
    year: 2008,
    required: false,
    vote: "5–4",
    amendments: ["2nd"],
    topics: ["Second Amendment", "individual rights"],
    unitId: "usgov-u3",
    cluster: "incorporation",
    issue: "Does the Second Amendment protect an individual right to possess a firearm unconnected with militia service?",
    background: "Dick Heller, a special police officer, challenged the District of Columbia's ban on handgun possession in the home.",
    decision: "The Court held that the Second Amendment protects an individual right to possess a firearm for traditionally lawful purposes, such as self-defense in the home.",
    principle: "The Second Amendment protects an individual right (applied to a federal enclave).",
    apRelevance: "Background for McDonald v. Chicago, which applied the right to the states.",
    related: [{ id: "mcdonald-v-chicago", relation: "Incorporated the right against states" }],
  },
  {
    id: "texas-v-johnson",
    name: "Texas v. Johnson",
    shortName: "Texas v. Johnson",
    year: 1989,
    required: false,
    vote: "5–4",
    amendments: ["1st", "14th"],
    topics: ["symbolic speech", "flag burning"],
    unitId: "usgov-u3",
    cluster: "speech-press",
    issue: "Is burning the American flag as political protest protected speech?",
    background: "Gregory Lee Johnson burned an American flag outside the 1984 Republican National Convention in Dallas and was convicted under a Texas law.",
    decision: "The Court held that flag burning is expressive conduct protected by the First Amendment.",
    principle: "Government may not prohibit expression simply because society finds it offensive.",
    apRelevance: "Common SCOTUS Comparison partner for Tinker (both symbolic speech).",
    related: [{ id: "tinker-v-des-moines", relation: "Symbolic speech" }],
  },
  {
    id: "morse-v-frederick",
    name: "Morse v. Frederick",
    shortName: "Morse",
    year: 2007,
    required: false,
    vote: "5–4",
    amendments: ["1st"],
    topics: ["student speech", "free speech"],
    unitId: "usgov-u3",
    cluster: "speech-press",
    issue: "May a public school restrict student speech reasonably viewed as promoting illegal drug use?",
    background: "At a school-supervised event in Juneau, Alaska, student Joseph Frederick displayed a banner reading \"BONG HiTS 4 JESUS.\" The principal confiscated it and suspended him.",
    decision: "The Court held that schools may restrict student speech at school events that is reasonably viewed as promoting illegal drug use.",
    principle: "Narrowed Tinker by recognizing an additional category of restrictable student speech.",
    apRelevance: "A classic non-required case for a Tinker SCOTUS Comparison question.",
    related: [{ id: "tinker-v-des-moines", relation: "Narrowed Tinker" }],
  },
  {
    id: "brandenburg-v-ohio",
    name: "Brandenburg v. Ohio",
    shortName: "Brandenburg",
    year: 1969,
    required: false,
    vote: "Unanimous (per curiam)",
    amendments: ["1st", "14th"],
    topics: ["free speech", "incitement", "imminent lawless action"],
    unitId: "usgov-u3",
    cluster: "speech-press",
    issue: "Can a state punish advocacy of violence that is not directed to inciting imminent lawless action?",
    background: "Clarence Brandenburg, a Ku Klux Klan leader, was convicted under an Ohio criminal syndicalism law for a speech at a rally.",
    decision:
      "The Court overturned the conviction, holding that advocacy may be punished only if it is directed to inciting imminent lawless action and is likely to produce such action.",
    principle: "The imminent lawless action test, replacing Schenck's clear and present danger standard.",
    apRelevance: "Shows how free speech doctrine evolved after Schenck.",
    related: [
      { id: "schenck-v-united-states", relation: "Replaced Schenck's test" },
      { id: "tinker-v-des-moines", relation: "Same era of expanding speech protection" },
    ],
  },
  {
    id: "reynolds-v-sims",
    name: "Reynolds v. Sims",
    shortName: "Reynolds",
    year: 1964,
    required: false,
    vote: "8–1",
    amendments: ["14th"],
    topics: ["one person one vote", "apportionment"],
    unitId: "usgov-u2",
    cluster: "elections",
    issue: "Must both houses of a state legislature be apportioned by population?",
    background: "Voters in Alabama challenged state legislative districts that had not been reapportioned in decades and were badly unequal in population.",
    decision: "The Court held that the Equal Protection Clause requires state legislative districts in both chambers to be roughly equal in population.",
    principle: "One person, one vote.",
    apRelevance: "Builds on Baker v. Carr; useful for redistricting SCOTUS Comparison questions.",
    related: [{ id: "baker-v-carr", relation: "Built on Baker's justiciability holding" }],
  },
  {
    id: "rucho-v-common-cause",
    name: "Rucho v. Common Cause",
    shortName: "Rucho",
    year: 2019,
    required: false,
    vote: "5–4",
    amendments: [],
    topics: ["partisan gerrymandering", "political question", "redistricting"],
    unitId: "usgov-u2",
    cluster: "elections",
    issue: "Can federal courts decide claims that partisan gerrymandering is unconstitutional?",
    background: "Voters challenged congressional maps in North Carolina and Maryland as extreme partisan gerrymanders.",
    decision: "The Court held that partisan gerrymandering claims present political questions beyond the reach of federal courts.",
    principle: "Partisan gerrymandering claims are nonjusticiable in federal court; remedies lie with states and Congress.",
    apRelevance: "A strong SCOTUS Comparison partner for Baker v. Carr — the two reach different conclusions about justiciability.",
    related: [
      { id: "baker-v-carr", relation: "Contrast: malapportionment held justiciable" },
      { id: "shaw-v-reno", relation: "Racial (not partisan) gerrymandering" },
    ],
  },
  {
    id: "buckley-v-valeo",
    name: "Buckley v. Valeo",
    shortName: "Buckley",
    year: 1976,
    required: false,
    amendments: ["1st"],
    topics: ["campaign finance", "contributions", "expenditures"],
    unitId: "usgov-u5",
    cluster: "elections",
    issue: "Do limits on campaign contributions and expenditures violate the First Amendment?",
    background: "After Watergate, Congress amended the Federal Election Campaign Act to limit contributions and spending. Senator James Buckley and others challenged the law.",
    decision:
      "The Court upheld limits on contributions to candidates but struck down limits on independent expenditures and on candidates' spending of their own money.",
    principle: "Spending money on political communication is protected speech; contribution limits can be justified to prevent corruption.",
    apRelevance: "The foundation for Citizens United's reasoning.",
    related: [{ id: "citizens-united-v-fec", relation: "Extended Buckley's reasoning" }],
  },
  {
    id: "kennedy-v-bremerton",
    name: "Kennedy v. Bremerton School District",
    shortName: "Kennedy",
    year: 2022,
    required: false,
    vote: "6–3",
    amendments: ["1st"],
    topics: ["Free Exercise Clause", "Establishment Clause", "school prayer"],
    unitId: "usgov-u3",
    cluster: "religion",
    issue: "May a public school discipline a coach for praying on the field after games?",
    background: "Joseph Kennedy, a high school football coach in Washington State, prayed at midfield after games. The district asked him to stop and later did not renew his contract.",
    decision:
      "The Court held that the coach's personal prayer was protected by the Free Exercise and Free Speech Clauses, and that the Establishment Clause should be interpreted by reference to historical practices and understandings.",
    principle: "Protected private religious expression by public employees; moved away from earlier Establishment Clause tests.",
    apRelevance: "A recent case to compare with Engel v. Vitale: government-sponsored prayer versus private prayer by an individual employee.",
    related: [{ id: "engel-v-vitale", relation: "Contrast: school-sponsored prayer" }],
  },
  {
    id: "sffa-v-harvard",
    name: "Students for Fair Admissions v. Harvard",
    shortName: "SFFA",
    year: 2023,
    required: false,
    vote: "6–3 (UNC); 6–2 (Harvard)",
    amendments: ["14th"],
    topics: ["affirmative action", "equal protection", "Civil Rights Act"],
    unitId: "usgov-u3",
    cluster: "equal-protection",
    issue: "Do race-conscious college admissions programs violate the Equal Protection Clause and Title VI of the Civil Rights Act?",
    background: "Students for Fair Admissions challenged the admissions programs of Harvard and the University of North Carolina, which considered race as one factor.",
    decision: "The Court held that the programs violated the Equal Protection Clause, effectively ending race-conscious admissions in higher education.",
    principle: "Race-conscious admissions programs must satisfy strict scrutiny, which these programs failed.",
    apRelevance: "Recent evidence for debates over equality of opportunity and equal protection.",
    related: [{ id: "brown-v-board", relation: "Equal protection and race" }],
  },
];

export const CASE_CLUSTERS: Record<CaseCluster, { label: string; description: string }> = {
  federalism: { label: "Federalism", description: "National vs. state power" },
  "judicial-power": { label: "Judicial Power", description: "The courts' role" },
  "speech-press": { label: "Speech & Press", description: "First Amendment expression" },
  religion: { label: "Religion", description: "Establishment & free exercise" },
  accused: { label: "Rights of the Accused", description: "4th, 5th, 6th Amendments" },
  incorporation: { label: "Incorporation", description: "Applying rights to states" },
  privacy: { label: "Privacy & Due Process", description: "Implied rights" },
  "equal-protection": { label: "Equal Protection", description: "Civil rights & race" },
  elections: { label: "Elections & Representation", description: "Districts & campaign finance" },
};
