/**
 * Generates SQL inserts for the optional content tables in supabase/schema.sql
 * from the typed content modules in src/content.
 *
 *   npm run seed:sql > supabase/seed.sql
 *
 * Also runs the content cross-reference validator and exits non-zero on
 * problems, so it doubles as a content lint step.
 */
import {
  CASES,
  COUNTRIES,
  COURSES,
  DOCUMENTS,
  FLASHCARDS,
  FRQS,
  LESSONS,
  QUESTIONS,
  UNITS,
  validateContent,
} from "../src/content";

const problems = validateContent();
if (problems.length) {
  console.error(`Content validation failed:\n- ${problems.join("\n- ")}`);
  process.exit(1);
}

const q = (v: unknown): string => {
  if (v === null || v === undefined) return "null";
  if (typeof v === "number" || typeof v === "boolean") return String(v);
  if (Array.isArray(v) && v.every((x) => typeof x === "string")) return `array[${v.map((x) => q(x)).join(",")}]::text[]`;
  if (typeof v === "object") return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
  return `'${String(v).replace(/'/g, "''")}'`;
};

const insert = (table: string, rows: Record<string, unknown>[]) => {
  if (!rows.length) return "";
  const cols = Object.keys(rows[0]);
  const values = rows.map((r) => `(${cols.map((c) => q(r[c])).join(", ")})`).join(",\n  ");
  return `insert into public.${table} (${cols.join(", ")}) values\n  ${values}\non conflict (id) do update set ${cols
    .filter((c) => c !== "id")
    .map((c) => `${c} = excluded.${c}`)
    .join(", ")};\n\n`;
};

let sql = "-- Generated by scripts/generate-seed.ts. Do not edit by hand.\nbegin;\n\n";
sql += insert(
  "courses",
  COURSES.map(({ id, title, ...rest }) => ({ id, title, data: rest })),
);
sql += insert(
  "units",
  UNITS.map((u) => ({ id: u.id, course_id: u.courseId, number: u.number, title: u.title, exam_weight: u.examWeight, weight_midpoint: u.weightMidpoint, lesson_ids: u.lessonIds })),
);
sql += insert(
  "lessons",
  LESSONS.map(({ id, courseId, unitId, title, minutes, tags, ...body }) => ({ id, course_id: courseId, unit_id: unitId, title, minutes, tags, body })),
);
sql += insert(
  "questions",
  QUESTIONS.map((x) => ({
    id: x.id,
    course_id: x.courseId,
    unit_id: x.unitId,
    topic_id: x.topicId,
    difficulty: x.difficulty,
    concept: x.concept,
    stem: x.stem,
    stimulus: x.stimulus ?? null,
    choices: x.choices,
    answer: x.answer,
    explanation: x.explanation,
    refs: { caseIds: x.caseIds ?? [], documentIds: x.documentIds ?? [], countryIds: x.countryIds ?? [] },
  })),
);
sql += insert(
  "flashcards",
  FLASHCARDS.map((f) => ({ id: f.id, course_id: f.courseId, deck: f.deck, front: f.front, back: f.back, unit_id: f.unitId ?? null })),
);
sql += insert(
  "frqs",
  FRQS.map(({ id, courseId, type, title, suggestedMinutes, ...data }) => ({ id, course_id: courseId, frq_type: type, title, suggested_minutes: suggestedMinutes, data })),
);
sql += insert(
  "supreme_court_cases",
  CASES.map(({ id, name, year, required, unitId, ...data }) => ({ id, name, year, required, unit_id: unitId, data })),
);
sql += insert(
  "foundational_documents",
  DOCUMENTS.map(({ id, title, addedIn, ...data }) => ({ id, title, added_in: addedIn ?? null, data })),
);
sql += insert(
  "countries",
  COUNTRIES.map(({ id, name, lastUpdated, ...data }) => ({ id, name, last_updated: lastUpdated, data })),
);
sql += "commit;\n";

process.stdout.write(sql);
console.error(
  `Seed: ${COURSES.length} courses, ${UNITS.length} units, ${LESSONS.length} lessons, ${QUESTIONS.length} questions, ${FLASHCARDS.length} flashcards, ${FRQS.length} FRQs, ${CASES.length} cases, ${DOCUMENTS.length} documents, ${COUNTRIES.length} countries.`,
);
